//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESVSnip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TESVSnip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _14_layer_deletelayer {
            get {
                object obj = ResourceManager.GetObject("14_layer_deletelayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_back {
            get {
                object obj = ResourceManager.GetObject("agt_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_forward {
            get {
                object obj = ResourceManager.GetObject("agt_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_stop {
            get {
                object obj = ResourceManager.GetObject("agt_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSureInquiry {
            get {
                return ResourceManager.GetString("AreYouSureInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_add {
            get {
                object obj = ResourceManager.GetObject("bookmark_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cut a plugin.
        /// </summary>
        internal static string Cannot_cut_a_plugin {
            get {
                return ResourceManager.GetString("Cannot_cut_a_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy nodes from different parents.
        /// </summary>
        internal static string CannotCopyNodesFromDifferentParents {
            get {
                return ResourceManager.GetString("CannotCopyNodesFromDifferentParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy a plugin.
        /// </summary>
        internal static string CannotCopyPlugin {
            get {
                return ResourceManager.GetString("CannotCopyPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot drag nodes with different parents.
        /// </summary>
        internal static string CannotDragNodesWithDifferentParents {
            get {
                return ResourceManager.GetString("CannotDragNodesWithDifferentParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot drop on descendant
        ///(think of the temporal paradoxes!).
        /// </summary>
        internal static string CannotDropOnDescendent {
            get {
                return ResourceManager.GetString("CannotDropOnDescendent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse RecordStructure.xml. Record-at-once editing will be unavailable.
        ///.
        /// </summary>
        internal static string CannotParseRecordStructure {
            get {
                return ResourceManager.GetString("CannotParseRecordStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subgroup structure of this plugins cell, world or dial records appears to be incorrect, and cannot be fixed automatically.
        /// </summary>
        internal static string CannotSanitizeLooseGroups {
            get {
                return ResourceManager.GetString("CannotSanitizeLooseGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin contained records which were not recognized, and cannot be fixed automatically.
        /// </summary>
        internal static string CannotSanitizeUnknownRecords {
            get {
                return ResourceManager.GetString("CannotSanitizeUnknownRecords", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap checkedbox {
            get {
                object obj = ResourceManager.GetObject("checkedbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkedbox1 {
            get {
                object obj = ResourceManager.GetObject("checkedbox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClearFiltering {
            get {
                object obj = ResourceManager.GetObject("ClearFiltering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close the active plugin, and you will lose any unsaved changes.
        ///Are you sure you wish to continue?.
        /// </summary>
        internal static string CloseActivePluginInquiry {
            get {
                return ResourceManager.GetString("CloseActivePluginInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close all open plugins, and you will lose any unsaved changes.
        ///Are you sure you wish to continue?.
        /// </summary>
        internal static string CloseAllLoseChangesInquiry {
            get {
                return ResourceManager.GetString("CloseAllLoseChangesInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ColumnFilterIndicator {
            get {
                object obj = ResourceManager.GetObject("ColumnFilterIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure_toolbars {
            get {
                object obj = ResourceManager.GetObject("configure_toolbars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Record to Clipboard.
        /// </summary>
        internal static string Copy_Record_to_Clipboard {
            get {
                return ResourceManager.GetString("Copy_Record_to_Clipboard", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deletecell {
            get {
                object obj = ResourceManager.GetObject("deletecell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_remove {
            get {
                object obj = ResourceManager.GetObject("edit_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editclear {
            get {
                object obj = ResourceManager.GetObject("editclear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditTable {
            get {
                object obj = ResourceManager.GetObject("EditTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emptybox {
            get {
                object obj = ResourceManager.GetObject("emptybox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is large size and takes significant memory to load.
        ///Would you like to apply the record exclusions?.
        /// </summary>
        internal static string ESM_Large_File_Size_Inquiry {
            get {
                return ResourceManager.GetString("ESM_Large_File_Size_Inquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fileexport {
            get {
                object obj = ResourceManager.GetObject("fileexport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Options.
        /// </summary>
        internal static string Filter_Options_Text {
            get {
                return ResourceManager.GetString("Filter_Options_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Filtering {
            get {
                object obj = ResourceManager.GetObject("Filtering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find2 {
            get {
                object obj = ResourceManager.GetObject("Find2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Load Options.
        /// </summary>
        internal static string FirstLoadOptions {
            get {
                return ResourceManager.GetString("FirstLoadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Record Editor.
        /// </summary>
        internal static string FullRecordEditorTitle {
            get {
                return ResourceManager.GetString("FullRecordEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don't know what this does, you probably don't want to click it
        ///Continue anyway?.
        /// </summary>
        internal static string GeneralSpellWarningInquiry {
            get {
                return ResourceManager.GetString("GeneralSpellWarningInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap insertcell {
            get {
                object obj = ResourceManager.GetObject("insertcell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap insertcell1 {
            get {
                object obj = ResourceManager.GetObject("insertcell1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadWarning {
            get {
                return ResourceManager.GetString("LoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first time 'skyrim.esm' has been loaded.
        ///The file is large size and takes significant memory to load.
        ///Would you like to configure which Records to exclude?.
        /// </summary>
        internal static string MainView_FirstTimeSkyrimLoad_ExcludeInquiry {
            get {
                return ResourceManager.GetString("MainView_FirstTimeSkyrimLoad_ExcludeInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Plugin.
        /// </summary>
        internal static string Missing_Plugin {
            get {
                return ResourceManager.GetString("Missing_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Record.
        /// </summary>
        internal static string Missing_Record {
            get {
                return ResourceManager.GetString("Missing_Record", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap move_task_down {
            get {
                object obj = ResourceManager.GetObject("move_task_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_task_up {
            get {
                object obj = ResourceManager.GetObject("move_task_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Plugins Loaded.
        /// </summary>
        internal static string No_Plugins_Loaded {
            get {
                return ResourceManager.GetString("No_Plugins_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin selected.
        /// </summary>
        internal static string NoPluginSelected {
            get {
                return ResourceManager.GetString("NoPluginSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin selected. Cannot continue..
        /// </summary>
        internal static string NoPluginSelectedCannotContinue {
            get {
                return ResourceManager.GetString("NoPluginSelectedCannotContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin selected to save.
        /// </summary>
        internal static string NoPluginSelectedToSave {
            get {
                return ResourceManager.GetString("NoPluginSelectedToSave", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin lacks a valid TES4 record. Cannot continue.
        /// </summary>
        internal static string PluginLacksAValidTes4RecordCannotContinue {
            get {
                return ResourceManager.GetString("PluginLacksAValidTes4RecordCannotContinue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap quick_restart {
            get {
                object obj = ResourceManager.GetObject("quick_restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_all_tabs {
            get {
                object obj = ResourceManager.GetObject("reload_all_tabs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm the coding setting, restart Tesvsnip now?.
        /// </summary>
        internal static string RestartText {
            get {
                return ResourceManager.GetString("RestartText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Revert {
            get {
                object obj = ResourceManager.GetObject("Revert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RolledBack {
            get {
                object obj = ResourceManager.GetObject("RolledBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has had a filter applied and contents potentially removed.  
        ///Do you still want to save?.
        /// </summary>
        internal static string SavePluginWithFilterAppliedInquiry {
            get {
                return ResourceManager.GetString("SavePluginWithFilterAppliedInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Found.
        /// </summary>
        internal static string SearchProgressChanged_Items_Found {
            get {
                return ResourceManager.GetString("SearchProgressChanged_Items_Found", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_paste {
            get {
                object obj = ResourceManager.GetObject("special_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon tesv_ico {
            get {
                object obj = ResourceManager.GetObject("tesv_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard is empty.
        /// </summary>
        internal static string TheClipboardIsEmpty {
            get {
                return ResourceManager.GetString("TheClipboardIsEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap xdays {
            get {
                object obj = ResourceManager.GetObject("xdays", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
