{******************************************************************************

  This Source Code Form is subject to the terms of the Mozilla Public License, 
  v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain 
  one at https://mozilla.org/MPL/2.0/.

*******************************************************************************}

{.$DEFINE USE_CODESITE}
{$DEFINE USE_PARALLEL_BUILD_REFS}

{$WARN IMPLICIT_STRING_CAST OFF}
{$WARN SYMBOL_PLATFORM OFF}

