{******************************************************************************

  This Source Code Form is subject to the terms of the Mozilla Public License,
  v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
  one at https://mozilla.org/MPL/2.0/.

*******************************************************************************}

unit wbDefinitionsSignatures;

interface

uses
  wbInterface;

const
  A0TX : TwbSignature = 'A0TX';
  AAAP : TwbSignature = 'AAAP'; { New To Fallout 76 }
  AACT : TwbSignature = 'AACT';
  AAMB : TwbSignature = 'AAMB'; { New To Starfield }
  AAMD : TwbSignature = 'AAMD'; { New To Fallout 76 }
  AAPD : TwbSignature = 'AAPD'; { New To Fallout 76 }
  AAPS : TwbSignature = 'AAPS'; { New To Fallout 76 }
  ABPO : TwbSignature = 'ABPO'; { New To Fallout 76 }
  ACBS : TwbSignature = 'ACBS';
  ACEC : TwbSignature = 'ACEC'; { New To Dawnguard }
  ACEP : TwbSignature = 'ACEP'; { New To Dawnguard }
  ACHR : TwbSignature = 'ACHR';
  ACID : TwbSignature = 'ACID'; { New To Dawnguard }
  ACPR : TwbSignature = 'ACPR'; { New To Skyrim }
  ACRE : TwbSignature = 'ACRE';
  ACSH : TwbSignature = 'ACSH'; { New To Starfield }
  ACSR : TwbSignature = 'ACSR'; { New To Dawnguard }
  ACTI : TwbSignature = 'ACTI';
  ACTV : TwbSignature = 'ACTV'; { New To Fallout 4 }
  ACUN : TwbSignature = 'ACUN'; { New To Dawnguard }
  ACUR : TwbSignature = 'ACUR'; { New To Starfield }
  ADBO : TwbSignature = 'ADBO';
  ADCR : TwbSignature = 'ADCR';
  ADDN : TwbSignature = 'ADDN';
  ADIA : TwbSignature = 'ADIA';
  AEAR : TwbSignature = 'AEAR'; { New To Starfield }
  AECH : TwbSignature = 'AECH'; { New To Fallout 4 }
  AFAV : TwbSignature = 'AFAV';
  AFFE : TwbSignature = 'AFFE'; { New To Starfield }
  AFSG : TwbSignature = 'AFSG'; { New To Starfield }
  AHCF : TwbSignature = 'AHCF'; { New To Skyrim }
  AHCM : TwbSignature = 'AHCM'; { New To Skyrim }
  AHEL : TwbSignature = 'AHEL';
  AIDT : TwbSignature = 'AIDT';
  AIID : TwbSignature = 'AIID';
  AIPL : TwbSignature = 'AIPL';
  AJLN : TwbSignature = 'AJLN'; { New To Fallout 76 }
  AJLO : TwbSignature = 'AJLO'; { New To Fallout 76 }
  AJLX : TwbSignature = 'AJLX'; { New To Fallout 76 }
  AJNG : TwbSignature = 'AJNG'; { New To Fallout 76 }
  AJOG : TwbSignature = 'AJOG'; { New To Fallout 76 }
  AJXG : TwbSignature = 'AJXG'; { New To Fallout 76 }
  ALAM : TwbSignature = 'ALAM'; { New To Starfield }
  ALCA : TwbSignature = 'ALCA'; { New To Skyrim }
  ALCC : TwbSignature = 'ALCC'; { New To Fallout 4 }
  ALCH : TwbSignature = 'ALCH';
  ALCL : TwbSignature = 'ALCL'; { New To Skyrim }
  ALCM : TwbSignature = 'ALCM'; { New To Starfield }
  ALCO : TwbSignature = 'ALCO'; { New To Skyrim }
  ALCS : TwbSignature = 'ALCS'; { New To Fallout 4 }
  ALDI : TwbSignature = 'ALDI'; { New To Fallout 4 }
  ALDN : TwbSignature = 'ALDN'; { New To Skyrim }
  ALEA : TwbSignature = 'ALEA'; { New To Skyrim }
  ALED : TwbSignature = 'ALED'; { New To Skyrim }
  ALEQ : TwbSignature = 'ALEQ'; { New To Skyrim }
  ALFA : TwbSignature = 'ALFA'; { New To Skyrim }
  ALFC : TwbSignature = 'ALFC'; { New To Skyrim }
  ALFD : TwbSignature = 'ALFD'; { New To Skyrim }
  ALFE : TwbSignature = 'ALFE'; { New To Skyrim }
  ALFF : TwbSignature = 'ALFF'; { New To Fallout 76 }
  ALFG : TwbSignature = 'ALFG'; { New To Starfield }
  ALFI : TwbSignature = 'ALFI'; { New To Skyrim }
  ALFL : TwbSignature = 'ALFL'; { New To Skyrim }
  ALFR : TwbSignature = 'ALFR'; { New To Skyrim }
  ALFT : TwbSignature = 'ALFT'; { New To Fallout 76 }
  ALFV : TwbSignature = 'ALFV'; { New To Fallout 4 }
  ALID : TwbSignature = 'ALID'; { New To Skyrim }
  ALKF : TwbSignature = 'ALKF'; { New To Starfield }
  ALLA : TwbSignature = 'ALLA'; { New To Fallout 4 }
  ALLR : TwbSignature = 'ALLR'; { New To Starfield }
  ALLS : TwbSignature = 'ALLS'; { New To Skyrim }
  ALMI : TwbSignature = 'ALMI'; { New To Fallout 4 }
  ALNA : TwbSignature = 'ALNA'; { New To Skyrim }
  ALNR : TwbSignature = 'ALNR'; { New To Starfield }
  ALNT : TwbSignature = 'ALNT'; { New To Skyrim }
  ALOC : TwbSignature = 'ALOC';
  ALPC : TwbSignature = 'ALPC'; { New To Skyrim }
  ALPN : TwbSignature = 'ALPN'; { New To Starfield }
  ALPS : TwbSignature = 'ALPS'; { New To Starfield }
  ALRT : TwbSignature = 'ALRT'; { New To Skyrim }
  ALSH : TwbSignature = 'ALSH'; { New To Starfield }
  ALSO : TwbSignature = 'ALSO'; { New To Fallout 76 }
  ALSP : TwbSignature = 'ALSP'; { New To Skyrim }
  ALST : TwbSignature = 'ALST'; { New To Skyrim }
  ALSY : TwbSignature = 'ALSY'; { New To Starfield }
  ALTM : TwbSignature = 'ALTM'; { New To Starfield }
  ALUA : TwbSignature = 'ALUA'; { New To Skyrim }
  ALUB : TwbSignature = 'ALUB'; { New To Starfield }
  AMBS : TwbSignature = 'AMBS'; { New To Starfield }
  AMDL : TwbSignature = 'AMDL'; { New To Fallout 4 }
  AMEF : TwbSignature = 'AMEF';
  AMMO : TwbSignature = 'AMMO';
  AMMR : TwbSignature = 'AMMR'; { New To Fallout 76 }
  AMRS : TwbSignature = 'AMRS'; { New To Fallout 76 }
  AMUS : TwbSignature = 'AMUS'; { New To Starfield }
  ANAM : TwbSignature = 'ANAM';
  ANIO : TwbSignature = 'ANIO';
  AOBJ : TwbSignature = 'AOBJ';
  AOPF : TwbSignature = 'AOPF'; { New To Starfield }
  AOPS : TwbSignature = 'AOPS'; { New To Starfield }
  AOR2 : TwbSignature = 'AOR2'; { New To Fallout 4 }
  AORU : TwbSignature = 'AORU'; { New To Fallout 4 }
  APPA : TwbSignature = 'APPA';
  APPR : TwbSignature = 'APPR'; { New To Fallout 4 }
  AQIC : TwbSignature = 'AQIC'; { New To Fallout 76 }
  ARMA : TwbSignature = 'ARMA';
  ARMO : TwbSignature = 'ARMO';
  ARRT : TwbSignature = 'ARRT';
  ARTC : TwbSignature = 'ARTC'; { New To Fallout 76 }
  ARTO : TwbSignature = 'ARTO';
  ASAE : TwbSignature = 'ASAE'; { New To Starfield }
  ASAS : TwbSignature = 'ASAS'; { New To Starfield }
  ASDF : TwbSignature = 'ASDF'; { New To Starfield }
  ASLS : TwbSignature = 'ASLS'; { New To Starfield }
  ASMB : TwbSignature = 'ASMB'; { New To Starfield }
  ASPC : TwbSignature = 'ASPC';
  ASSU : TwbSignature = 'ASSU';
  ASTM : TwbSignature = 'ASTM'; { New To Fallout 76 }
  ASTP : TwbSignature = 'ASTP';
  ATAC : TwbSignature = 'ATAC'; { New To Starfield }
  ATAF : TwbSignature = 'ATAF'; { New To Starfield }
  ATAN : TwbSignature = 'ATAN'; { New To Starfield }
  ATAT : TwbSignature = 'ATAT'; { New to Fallout 76 }
  ATAV : TwbSignature = 'ATAV'; { New To Starfield }
  ATCP : TwbSignature = 'ATCP'; { New To Starfield }
  ATKD : TwbSignature = 'ATKD'; { New to Skyrim }
  ATKE : TwbSignature = 'ATKE'; { New to Skyrim }
  ATKR : TwbSignature = 'ATKR'; { New to Skyrim }
  ATKS : TwbSignature = 'ATKS'; { New To Fallout 4 }
  ATKT : TwbSignature = 'ATKT'; { New To Fallout 4 }
  ATKW : TwbSignature = 'ATKW'; { New To Fallout 4 }
  ATMO : TwbSignature = 'ATMO'; { New To Starfield }
  ATSI : TwbSignature = 'ATSI'; { New to Fallout 76 }
  ATTN : TwbSignature = 'ATTN'; { New To Fallout 4 }
  ATTR : TwbSignature = 'ATTR'; { New To Fallout 76 }
  ATTX : TwbSignature = 'ATTX'; { New To Fallout 4 }
  ATXO : TwbSignature = 'ATXO'; { New To Fallout 76 }
  ATXT : TwbSignature = 'ATXT';
  AUUV : TwbSignature = 'AUUV'; { New To Fallout 76 }
  AUVF : TwbSignature = 'AUVF'; { New To Fallout 76. Found in EXE GRUP order. added in patch 1.2.2.1 }
  AVFL : TwbSignature = 'AVFL'; { New To Fallout 4 }
  AVIF : TwbSignature = 'AVIF';
  AVMD : TwbSignature = 'AVMD'; { New To Starfield }
  AVMG : TwbSignature = 'AVMG'; { New To Fallout 76 }
  AVSG : TwbSignature = 'AVSG'; { New To Starfield }
  AVSK : TwbSignature = 'AVSK'; { New to Skyrim }
  AVTR : TwbSignature = 'AVTR'; { New To Fallout 76 }
  AWSD : TwbSignature = 'AWSD'; { New To Fallout 76 }
  B0TX : TwbSignature = 'B0TX';
  BAMT : TwbSignature = 'BAMT'; { New to Skyrim }
  BCLF : TwbSignature = 'BCLF'; { New to Fallout 4 }
  BCOL : TwbSignature = 'BCOL'; { New To Starfield }
  BDED : TwbSignature = 'BDED'; { New To Starfield }
  BDFS : TwbSignature = 'BDFS'; { New To Starfield }
  BDST : TwbSignature = 'BDST'; { New To Starfield }
  BETH : TwbSignature = 'BETH'; { New To Starfield }
  BEVA : TwbSignature = 'BEVA'; { New To Fallout 76 }
  BFCB : TwbSignature = 'BFCB'; { New To Starfield }
  BFCE : TwbSignature = 'BFCE'; { New To Starfield }
  BIAS : TwbSignature = 'BIAS'; { New To Starfield }
  BIDS : TwbSignature = 'BIDS'; { New to Skyrim }
  BIMT : TwbSignature = 'BIMT'; { New To Starfield }
  BIOM : TwbSignature = 'BIOM'; { New To Starfield }
  BIPL : TwbSignature = 'BIPL';
  BLUF : TwbSignature = 'BLUF'; { New To Starfield }
  BMC1 : TwbSignature = 'BMC1'; { New To Starfield }
  BMC2 : TwbSignature = 'BMC2'; { New To Starfield }
  BMC3 : TwbSignature = 'BMC3'; { New To Starfield }
  BMCT : TwbSignature = 'BMCT';
  BMDT : TwbSignature = 'BMDT';
  BMMO : TwbSignature = 'BMMO'; { New To Starfield }
  BMMP : TwbSignature = 'BMMP'; { New to Fallout 4 }
  BMOD : TwbSignature = 'BMOD'; { New To Starfield }
  BMPN : TwbSignature = 'BMPN'; { New To Starfield }
  BMPP : TwbSignature = 'BMPP'; { New To Starfield }
  BMPV : TwbSignature = 'BMPV'; { New To Starfield }
  BNAM : TwbSignature = 'BNAM';
  BNDS : TwbSignature = 'BNDS'; { New to Fallout 4 }
  BO64 : TwbSignature = 'BO64'; { New To Starfield }
  BOD2 : TwbSignature = 'BOD2'; { New to Skyrim 1.6.91 CK}
  BODC : TwbSignature = 'BODC'; { New To Starfield }
  BODM : TwbSignature = 'BODM'; { New To Starfield }
  BODS : TwbSignature = 'BODS'; { New To Starfield }
  BODT : TwbSignature = 'BODT'; { New to Skyrim }
  BODV : TwbSignature = 'BODV'; { New To Starfield }
  BOID : TwbSignature = 'BOID'; { New To Starfield }
  BOLV : TwbSignature = 'BOLV'; { New To Starfield }
  BOOK : TwbSignature = 'BOOK';
  BPD2 : TwbSignature = 'BPD2'; { New To Starfield }
  BPND : TwbSignature = 'BPND';
  BPNI : TwbSignature = 'BPNI';
  BPNN : TwbSignature = 'BPNN';
  BPNT : TwbSignature = 'BPNT';
  BPTD : TwbSignature = 'BPTD';
  BPTN : TwbSignature = 'BPTN';
  BPVB : TwbSignature = 'BPVB'; { New to Fallout 76 }
  BRIB : TwbSignature = 'BRIB';
  BRUS : TwbSignature = 'BRUS';
  BSIZ : TwbSignature = 'BSIZ'; { New to Fallout 4 }
  BSMB : TwbSignature = 'BSMB'; { New to Fallout 4 }
  BSMP : TwbSignature = 'BSMP'; { New to Fallout 4 }
  BSMS : TwbSignature = 'BSMS'; { New to Fallout 4 }
  BSTT : TwbSignature = 'BSTT'; { New To Starfield }
  BTOF : TwbSignature = 'BTOF'; { New to Fallout 76 }
  BTPS : TwbSignature = 'BTPS'; { New To Starfield }
  BTXT : TwbSignature = 'BTXT';
  BUO4 : TwbSignature = 'BUO4'; { New To Starfield }
  BVGO : TwbSignature = 'BVGO'; { New to Fallout 76 }
  C0TX : TwbSignature = 'C0TX';
  CAMS : TwbSignature = 'CAMS';
  CARD : TwbSignature = 'CARD';
  CAST : TwbSignature = 'CAST';
  CBGN : TwbSignature = 'CBGN'; { New to Fallout 76 }
  CCRD : TwbSignature = 'CCRD';
  CDCK : TwbSignature = 'CDCK';
  CDIX : TwbSignature = 'CDIX'; { New to Fallout 4 }
  CDND : TwbSignature = 'CDND'; { New To Starfield }
  CDNS : TwbSignature = 'CDNS'; { New To Starfield }
  CELL : TwbSignature = 'CELL';
  CENT : TwbSignature = 'CENT'; { New To Fallout 76 }
  CHAL : TwbSignature = 'CHAL'; { New To Fallout 76 }
  CHGL : TwbSignature = 'CHGL'; { New To Starfield }
  CHIP : TwbSignature = 'CHIP';
  CHRR : TwbSignature = 'CHRR';
  CIDH : TwbSignature = 'CIDH'; { New to Fallout 76 }
  CIFK : TwbSignature = 'CIFK'; { New to Fallout 76 }
  CII0 : TwbSignature = 'CII0'; { New to Fallout 76 }
  CIS1 : TwbSignature = 'CIS1'; { New to Skyrim }
  CIS2 : TwbSignature = 'CIS2'; { New to Skyrim }
  CITC : TwbSignature = 'CITC'; { New to Skyrim }
  CLAS : TwbSignature = 'CLAS';
  CLDC : TwbSignature = 'CLDC';
  CLDF : TwbSignature = 'CLDF'; { New To Starfield }
  CLFM : TwbSignature = 'CLFM';
  CLMT : TwbSignature = 'CLMT';
  CLOC : TwbSignature = 'CLOC';
  CLRL : TwbSignature = 'CLRL';
  CLSZ : TwbSignature = 'CLSZ'; { New to Fallout 4 }
  CMIC : TwbSignature = 'CMIC'; { New To Fallout 76 }
  CMNY : TwbSignature = 'CMNY';
  CMPO : TwbSignature = 'CMPO'; { New to Fallout 4 }
  CNAM : TwbSignature = 'CNAM';
  CNCY : TwbSignature = 'CNCY'; { New To Fallout 76 }
  CNDC : TwbSignature = 'CNDC'; { New To Fallout 76 }
  CNDF : TwbSignature = 'CNDF'; { New To Fallout 76 }
  CNTO : TwbSignature = 'CNTO';
  COBJ : TwbSignature = 'COBJ';
  COCT : TwbSignature = 'COCT'; { New to Skyrim 'Count'}
  CODV : TwbSignature = 'CODV'; { New To Fallout 76 }
  COED : TwbSignature = 'COED';
  COEN : TwbSignature = 'COEN'; { New To Fallout 76 }
  COLL : TwbSignature = 'COLL';
  CONT : TwbSignature = 'CONT';
  CPRD : TwbSignature = 'CPRD'; { New to Fallout 76 }
  CPTH : TwbSignature = 'CPTH';
  CRDT : TwbSignature = 'CRDT';
  CREA : TwbSignature = 'CREA';
  CRFT : TwbSignature = 'CRFT';
  CRGP : TwbSignature = 'CRGP'; { New To Starfield }
  CRGR : TwbSignature = 'CRGR'; { New to Skyrim }
  CRHR : TwbSignature = 'CRHR'; { New To Starfield }
  CRIF : TwbSignature = 'CRIF'; { New to Skyrim }
  CRIS : TwbSignature = 'CRIS'; { New to Fallout 4 }
  CRTY : TwbSignature = 'CRTY'; { New To Fallout 76 }
  CRVA : TwbSignature = 'CRVA'; { New to Skyrim }
  CRVE : TwbSignature = 'CRVE'; { New To Fallout 76 }
  CS2D : TwbSignature = 'CS2D'; { New To Fallout 4 }
  CS2E : TwbSignature = 'CS2E'; { New To Fallout 4 }
  CS2F : TwbSignature = 'CS2F'; { New To Fallout 4 }
  CS2H : TwbSignature = 'CS2H'; { New To Fallout 4 }
  CS2K : TwbSignature = 'CS2K'; { New To Fallout 4 }
  CS3E : TwbSignature = 'CS3E'; { New To Starfield }
  CS3F : TwbSignature = 'CS3F'; { New To Starfield }
  CS3H : TwbSignature = 'CS3H'; { New To Starfield }
  CS3K : TwbSignature = 'CS3K'; { New To Starfield }
  CS3S : TwbSignature = 'CS3S'; { New To Starfield }
  CSAD : TwbSignature = 'CSAD';
  CSCR : TwbSignature = 'CSCR';
  CSCV : TwbSignature = 'CSCV'; { New To Fallout 4 }
  CSDC : TwbSignature = 'CSDC';
  CSDI : TwbSignature = 'CSDI';
  CSDT : TwbSignature = 'CSDT';
  CSEN : TwbSignature = 'CSEN'; { New To Fallout 76 }
  CSFL : TwbSignature = 'CSFL'; { New to Skyrim }
  CSGD : TwbSignature = 'CSGD'; { New to Skyrim }
  CSLR : TwbSignature = 'CSLR'; { New to Skyrim }
  CSMD : TwbSignature = 'CSMD'; { New to Skyrim }
  CSME : TwbSignature = 'CSME'; { New to Skyrim }
  CSNO : TwbSignature = 'CSNO';
  CSRA : TwbSignature = 'CSRA'; { New To Fallout 4 }
  CSSA : TwbSignature = 'CSSA'; { New To Starfield }
  CSSD : TwbSignature = 'CSSD';
  CSSG : TwbSignature = 'CSSG'; { New To Starfield }
  CSSM : TwbSignature = 'CSSM'; { New To Starfield }
  CSSR : TwbSignature = 'CSSR'; { New To Starfield }
  CSTD : TwbSignature = 'CSTD';
  CSTG : TwbSignature = 'CSTG'; { New To Fallout 76 }
  CSTN : TwbSignature = 'CSTN'; { New To Starfield }
  CSTY : TwbSignature = 'CSTY';
  CTDA : TwbSignature = 'CTDA';
  CTRG : TwbSignature = 'CTRG'; { New To Fallout 76 }
  CTRN : TwbSignature = 'CTRN'; { New To Fallout 76 0.2.838.0 }
  CUR3 : TwbSignature = 'CUR3'; { New To Starfield }
  CURE : TwbSignature = 'CURE';
  CURV : TwbSignature = 'CURV'; { New To Fallout 76 }
  CUSD : TwbSignature = 'CUSD'; { New to Fallout 4 }
  CUSH : TwbSignature = 'CUSH'; { New To Starfield }
  CVPA : TwbSignature = 'CVPA'; { New to Fallout 4 }
  CVT0 : TwbSignature = 'CVT0'; { New to Fallout 76 }
  CVT1 : TwbSignature = 'CVT1'; { New To Fallout 76 }
  CVT2 : TwbSignature = 'CVT2'; { New To Fallout 76 }
  CVT3 : TwbSignature = 'CVT3'; { New To Fallout 76 }
  CVT4 : TwbSignature = 'CVT4'; { New To Fallout 76 }
  CVT5 : TwbSignature = 'CVT5'; { New To Fallout 76 }
  D0TX : TwbSignature = 'D0TX';
  DALC : TwbSignature = 'DALC'; { New to Skyrim }
  DAMA : TwbSignature = 'DAMA'; { New to Fallout 4 }
  DAMC : TwbSignature = 'DAMC'; { New to Fallout 4 }
  DAMS : TwbSignature = 'DAMS'; { New To Fallout 76 }
  DAT2 : TwbSignature = 'DAT2';
  DATA : TwbSignature = 'DATA';
  DCED : TwbSignature = 'DCED'; { New To Starfield }
  DCGB : TwbSignature = 'DCGB'; { New To Fallout 76 }
  DCGF : TwbSignature = 'DCGF'; { New To Fallout 76 }
  DCGL : TwbSignature = 'DCGL'; { New To Fallout 76 }
  DCGQ : TwbSignature = 'DCGQ'; { New To Fallout 76 }
  DCGS : TwbSignature = 'DCGS'; { New To Fallout 76 }
  DCLL : TwbSignature = 'DCLL'; { New To Fallout 76 }
  DCSD : TwbSignature = 'DCSD'; { New To Starfield }
  DCSH : TwbSignature = 'DCSH'; { New To Starfield }
  DEAD : TwbSignature = 'DEAD';
  DEBR : TwbSignature = 'DEBR';
  DEFL : TwbSignature = 'DEFL'; { New To Fallout 76 }
  DEHY : TwbSignature = 'DEHY';
  DELE : TwbSignature = 'DELE';
  DEMO : TwbSignature = 'DEMO'; { New to Skyrim }
  DENS : TwbSignature = 'DENS'; { New To Starfield }
  DESC : TwbSignature = 'DESC';
  DEST : TwbSignature = 'DEST';
  DEVA : TwbSignature = 'DEVA'; { New to Skyrim }
  DEVT : TwbSignature = 'DEVT'; { New To Starfield }
  DFOB : TwbSignature = 'DFOB'; { New to Fallout 4 }
  DFTF : TwbSignature = 'DFTF'; { New To Skyrim }
  DFTM : TwbSignature = 'DFTM'; { New To Skyrim }
  DIAL : TwbSignature = 'DIAL';
  DIFF : TwbSignature = 'DIFF'; { New To Starfield }
  DICO : TwbSignature = 'DICO'; { New to Fallout 76 }
  DIMG : TwbSignature = 'DIMG'; { New to Fallout 76 }
  DIQO : TwbSignature = 'DIQO'; { New To Fallout 76 }
  DIST : TwbSignature = 'DIST'; { New To Fallout 76 }
  DLBR : TwbSignature = 'DLBR';
  DLSH : TwbSignature = 'DLSH'; { New To Starfield }
  DLVW : TwbSignature = 'DLVW';
  DLYR : TwbSignature = 'DLYR'; { New to Fallout 76. Found in EXE GRUP order }
  DMAX : TwbSignature = 'DMAX'; { New to Skyrim }
  DMDC : TwbSignature = 'DMDC'; { New to Fallout 4 }
  DMDL : TwbSignature = 'DMDL';
  DMDS : TwbSignature = 'DMDS'; { New to Skyrim }
  DMDT : TwbSignature = 'DMDT';
  DMGT : TwbSignature = 'DMGT'; { New to Fallout 4 }
  DMIN : TwbSignature = 'DMIN'; { New to Skyrim }
  DNAM : TwbSignature = 'DNAM';
  DOBJ : TwbSignature = 'DOBJ';
  DOCK : TwbSignature = 'DOCK'; { New To Starfield }
  DODT : TwbSignature = 'DODT';
  DOFA : TwbSignature = 'DOFA'; { New To Fallout 76 }
  DOFT : TwbSignature = 'DOFT'; { New to Skyrim }
  DOOR : TwbSignature = 'DOOR';
  DOSH : TwbSignature = 'DOSH'; { New To Starfield }
  DPLT : TwbSignature = 'DPLT'; { New to Skyrim }
  DPOS : TwbSignature = 'DPOS'; { New to Fallout 76 }
  DPRT : TwbSignature = 'DPRT'; { New to Fallout 76 }
  DQST : TwbSignature = 'DQST'; { New to Fallout 76 }
  DSCF : TwbSignature = 'DSCF'; { New To Fallout 76 }
  DSDL : TwbSignature = 'DSDL'; { New To Starfield }
  DSTA : TwbSignature = 'DSTA'; { New To Fallout 4 }
  DSTD : TwbSignature = 'DSTD';
  DSTF : TwbSignature = 'DSTF';
  DTGT : TwbSignature = 'DTGT'; { New To Fallout 4 }
  DTID : TwbSignature = 'DTID'; { New To Fallout 4 }
  DUAL : TwbSignature = 'DUAL';
  DURG : TwbSignature = 'DURG'; { New To Fallout 76 }
  DURL : TwbSignature = 'DURL'; { New To Fallout 76 }
  E0TX : TwbSignature = 'E0TX';
  EAMT : TwbSignature = 'EAMT';
  ECAT : TwbSignature = 'ECAT'; { New To Fallout 76 }
  ECHD : TwbSignature = 'ECHD'; { New To Fallout 76 }
  ECHE : TwbSignature = 'ECHE'; { New To Fallout 76 }
  ECHL : TwbSignature = 'ECHL'; { New To Starfield }
  ECHO : TwbSignature = 'ECHO'; { New To Fallout 76 }
  ECIL : TwbSignature = 'ECIL'; { New To Fallout 76 }
  ECOL : TwbSignature = 'ECOL'; { New To Starfield }
  ECOR : TwbSignature = 'ECOR'; { New to Skyrim }
  ECSH : TwbSignature = 'ECSH'; { New To Starfield }
  ECTE : TwbSignature = 'ECTE'; { New To Starfield }
  ECZN : TwbSignature = 'ECZN';
  EDCT : TwbSignature = 'EDCT'; { New To Starfield }
  EDID : TwbSignature = 'EDID';
  EFID : TwbSignature = 'EFID';
  EFIF : TwbSignature = 'EFIF'; { New To Starfield }
  EFIT : TwbSignature = 'EFIT';
  EFSD : TwbSignature = 'EFSD';
  EFSH : TwbSignature = 'EFSH';
  EFSQ : TwbSignature = 'EFSQ'; { New To Starfield }
  EIES : TwbSignature = 'EIES'; { New To Fallout 76 0.2.626.7 }
  EILV : TwbSignature = 'EILV'; { New To Fallout 76 }
  EITM : TwbSignature = 'EITM';
  EMOT : TwbSignature = 'EMOT'; { New To Fallout 76 }
  ENAM : TwbSignature = 'ENAM';
  ENCH : TwbSignature = 'ENCH';
  ENIT : TwbSignature = 'ENIT';
  ENLM : TwbSignature = 'ENLM'; { New To Fallout 76 }
  ENLS : TwbSignature = 'ENLS'; { New To Fallout 76 }
  ENLT : TwbSignature = 'ENLT'; { New To Fallout 76 }
  ENTM : TwbSignature = 'ENTM'; { New To Fallout 76 }
  EPCD : TwbSignature = 'EPCD'; { New To Fallout 76 0.2.782.0 }
  EPEG : TwbSignature = 'EPEG'; { New To Fallout 76 0.2.782.0 }
  EPF2 : TwbSignature = 'EPF2';
  EPF3 : TwbSignature = 'EPF3';
  EPF4 : TwbSignature = 'EPF4';
  EPFB : TwbSignature = 'EPFB'; { New To Fallout 4 }
  EPFD : TwbSignature = 'EPFD';
  EPFL : TwbSignature = 'EPFL'; { New To Fallout 76 0.2.782.0 }
  EPFT : TwbSignature = 'EPFT';
  EPNQ : TwbSignature = 'EPNQ'; { New To Fallout 76 0.2.782.0 }
  EPPR : TwbSignature = 'EPPR'; { New To Fallout 76 0.2.782.0 }
  EPQA : TwbSignature = 'EPQA'; { New To Fallout 76 0.2.782.0 }
  EPSI : TwbSignature = 'EPSI'; { New To Fallout 76 0.2.782.0 }
  EQUP : TwbSignature = 'EQUP';
  EQWG : TwbSignature = 'EQWG'; { New To Fallout 76. In Exe Grup Order }
  ESAV : TwbSignature = 'ESAV'; { New To Fallout 76 }
  ESCE : TwbSignature = 'ESCE';
  ESCR : TwbSignature = 'ESCR'; { New To Fallout 76 }
  ESCS : TwbSignature = 'ESCS'; { New To Fallout 76 }
  ESDA : TwbSignature = 'ESDA'; { New To Fallout 76 }
  ESJA : TwbSignature = 'ESJA';
  ESRE : TwbSignature = 'ESRE'; { New To Fallout 76 }
  ESRP : TwbSignature = 'ESRP'; { New To Fallout 76 }
  ESRV : TwbSignature = 'ESRV'; { New To Fallout 76 }
  ESSF : TwbSignature = 'ESSF'; { New To Starfield }
  ESSH : TwbSignature = 'ESSH'; { New To Starfield }
  ETDI : TwbSignature = 'ETDI'; { New To Fallout 76 }
  ETIP : TwbSignature = 'ETIP'; { New To Fallout 76 }
  ETLG : TwbSignature = 'ETLG'; { New To Fallout 76 }
  ETRG : TwbSignature = 'ETRG'; { New To Fallout 76 }
  ETYP : TwbSignature = 'ETYP';
  EXAC : TwbSignature = 'EXAC'; { New To Starfield }
  EXAS : TwbSignature = 'EXAS'; { New To Starfield }
  EXBS : TwbSignature = 'EXBS'; { New To Starfield }
  EXCI : TwbSignature = 'EXCI'; { New To Starfield }
  EXCN : TwbSignature = 'EXCN'; { New To Starfield }
  EXDC : TwbSignature = 'EXDC'; { New To Starfield }
  EXDZ : TwbSignature = 'EXDZ'; { New To Starfield }
  EXPL : TwbSignature = 'EXPL';
  EYES : TwbSignature = 'EYES';
  F0TX : TwbSignature = 'F0TX';
  FACT : TwbSignature = 'FACT';
  FCHT : TwbSignature = 'FCHT'; { New to Skyrim }
  FCPL : TwbSignature = 'FCPL'; { New To Fallout 4 }
  FCTF : TwbSignature = 'FCTF'; { New To Starfield }
  FCTP : TwbSignature = 'FCTP'; { New To Starfield }
  FDDS : TwbSignature = 'FDDS'; { New To Starfield }
  FDSI : TwbSignature = 'FDSI'; { New To Starfield }
  FDSL : TwbSignature = 'FDSL'; { New To Starfield }
  FEVA : TwbSignature = 'FEVA'; { New To Fallout 76 }
  FFEF : TwbSignature = 'FFEF'; { New To Fallout 76 }
  FFFF : TwbSignature = 'FFFF';
  FFKW : TwbSignature = 'FFKW'; { New to Starfield }
  FGGA : TwbSignature = 'FGGA';
  FGGS : TwbSignature = 'FGGS';
  FGTS : TwbSignature = 'FGTS';
  FHCL : TwbSignature = 'FHCL'; { New To Starfield }
  FHLS : TwbSignature = 'FHLS'; { New To Starfield }
  FIMD : TwbSignature = 'FIMD'; { New To Fallout 4 }
  FLAD : TwbSignature = 'FLAD'; { New To Starfield }
  FLAG : TwbSignature = 'FLAG'; { New To Starfield }
  FLAT : TwbSignature = 'FLAT';
  FLAV : TwbSignature = 'FLAV'; { New To Starfield }
  FLBD : TwbSignature = 'FLBD'; { New To Starfield }
  FLCS : TwbSignature = 'FLCS'; { New To Starfield }
  FLEE : TwbSignature = 'FLEE'; { New To Starfield }
  FLFG : TwbSignature = 'FLFG'; { New To Fallout 76 }
  FLFM : TwbSignature = 'FLFM'; { New To Starfield }
  FLGD : TwbSignature = 'FLGD'; { New To Starfield }
  FLKW : TwbSignature = 'FLKW'; { New To Starfield }
  FLLD : TwbSignature = 'FLLD'; { New To Starfield }
  FLMV : TwbSignature = 'FLMV'; { New to Skyrim }
  FLOR : TwbSignature = 'FLOR';
  FLRD : TwbSignature = 'FLRD'; { New To Starfield }
  FLST : TwbSignature = 'FLST';
  FLTR : TwbSignature = 'FLTR'; { New to Skyrim }
  FLTV : TwbSignature = 'FLTV';
  FLXP : TwbSignature = 'FLXP'; { New To Starfield }
  FMAG : TwbSignature = 'FMAG'; { New To Fallout 76 }
  FMAH : TwbSignature = 'FMAH'; { New To Fallout 76 }
  FMIG : TwbSignature = 'FMIG'; { New To Fallout 76 }
  FMIH : TwbSignature = 'FMIH'; { New To Fallout 76 }
  FMIN : TwbSignature = 'FMIN'; { New To Fallout 4 }
  FMRG : TwbSignature = 'FMRG'; { New To Starfield }
  FMRI : TwbSignature = 'FMRI'; { New To Fallout 4 }
  FMRN : TwbSignature = 'FMRN'; { New To Fallout 4 }
  FMRS : TwbSignature = 'FMRS'; { New To Fallout 4 }
  FMRU : TwbSignature = 'FMRU'; { New To Starfield }
  FMSI : TwbSignature = 'FMSI'; { New To Starfield }
  FMSR : TwbSignature = 'FMSR'; { New To Starfield }
  FNAM : TwbSignature = 'FNAM';
  FNMK : TwbSignature = 'FNMK'; { New to Skyrim }
  FNMU : TwbSignature = 'FNMU'; { New To Fallout 76 }
  FNPR : TwbSignature = 'FNPR'; { New to Skyrim }
  FOGV : TwbSignature = 'FOGV'; { New To Starfield }
  FORC : TwbSignature = 'FORC'; { New To Starfield }
  FPRT : TwbSignature = 'FPRT'; { New to Skyrim }
  FSTP : TwbSignature = 'FSTP';
  FSTS : TwbSignature = 'FSTS';
  FSTT : TwbSignature = 'FSTT'; { New To Starfield }
  FTAG : TwbSignature = 'FTAG'; { New To Fallout 76 }
  FTMP : TwbSignature = 'FTMP'; { New To Starfield }
  FTSF : TwbSignature = 'FTSF'; { New to Skyrim }
  FTSM : TwbSignature = 'FTSM'; { New to Skyrim }
  FTST : TwbSignature = 'FTST'; { New to Skyrim }
  FTYP : TwbSignature = 'FTYP'; { New To Fallout 4 }
  FULL : TwbSignature = 'FULL';
  FURN : TwbSignature = 'FURN';
  FVLD : TwbSignature = 'FVLD'; { New To Starfield }
  FVPA : TwbSignature = 'FVPA'; { New To Fallout 4 }
  FXPD : TwbSignature = 'FXPD'; { New To Starfield }
  G0TX : TwbSignature = 'G0TX';
  GBFM : TwbSignature = 'GBFM'; { New To Starfield }
  GBFT : TwbSignature = 'GBFT'; { New To Starfield }
  GCDA : TwbSignature = 'GCDA'; { New To Fallout 76 }
  GCVR : TwbSignature = 'GCVR'; { New To Fallout 76 }
  GDRY : TwbSignature = 'GDRY'; { New to Fallout 4; Unused in Fallout 76 but exists in SeventySix.esm }
  GLOB : TwbSignature = 'GLOB';
  GMRW : TwbSignature = 'GMRW'; { New to Fallout 76 0.2.782.0 }
  GMST : TwbSignature = 'GMST';
  GNAM : TwbSignature = 'GNAM';
  GRAS : TwbSignature = 'GRAS';
  GREE : TwbSignature = 'GREE'; { New to Fallout 4 }
  GOGL : TwbSignature = 'GOGL'; { New To Starfield }
  GPOD : TwbSignature = 'GPOD'; { New To Starfield }
  GPOF : TwbSignature = 'GPOF'; { New To Starfield }
  GPOG : TwbSignature = 'GPOG'; { New To Starfield }
  GRPH : TwbSignature = 'GRPH'; { New To Starfield }
  GWOR : TwbSignature = 'GWOR'; { New to Skyrim }
  H0TX : TwbSignature = 'H0TX';
  HACK : TwbSignature = 'HACK';
  HAIR : TwbSignature = 'HAIR';
  HAZD : TwbSignature = 'HAZD';
  HCLF : TwbSignature = 'HCLF'; { New to Skyrim }
  HCLR : TwbSignature = 'HCLR';
  HCOL : TwbSignature = 'HCOL'; { New To Starfield }
  HDPT : TwbSignature = 'HDPT';
  HEAD : TwbSignature = 'HEAD'; { New to Skyrim }
  HEDR : TwbSignature = 'HEDR';
  HEFA : TwbSignature = 'HEFA'; { New To Starfield }
  HERD : TwbSignature = 'HERD'; { New To Starfield }
  HGLB : TwbSignature = 'HGLB'; { New To Fallout 76 }
  HLTX : TwbSignature = 'HLTX'; { New to Fallout 4 }
  HNAM : TwbSignature = 'HNAM';
  HSTT : TwbSignature = 'HSTT'; { New To Starfield }
  HTID : TwbSignature = 'HTID'; { New to Skyrim }
  HULL : TwbSignature = 'HULL'; { New To Starfield }
  HUNG : TwbSignature = 'HUNG';
  I0TX : TwbSignature = 'I0TX';
  IBIN : TwbSignature = 'IBIN'; { New To Starfield }
  IBSD : TwbSignature = 'IBSD'; { New To Fallout 76 }
  ICO2 : TwbSignature = 'ICO2';
  ICON : TwbSignature = 'ICON';
  IDLA : TwbSignature = 'IDLA';
  IDLB : TwbSignature = 'IDLB';
  IDLC : TwbSignature = 'IDLC';
  IDLE : TwbSignature = 'IDLE';
  IDLF : TwbSignature = 'IDLF';
  IDLM : TwbSignature = 'IDLM';
  IDLT : TwbSignature = 'IDLT';
  IDP1 : TwbSignature = 'IDP1'; { New To Starfield }
  IDP3 : TwbSignature = 'IDP3'; { New To Starfield }
  IDSH : TwbSignature = 'IDSH'; { New To Starfield }
  IKEK : TwbSignature = 'IKEK'; { New To Fallout 76 }
  ILAC : TwbSignature = 'ILAC'; { New To Fallout 76 }
  ILOC : TwbSignature = 'ILOC';
  IMAD : TwbSignature = 'IMAD';
  IMGS : TwbSignature = 'IMGS';
  IMOD : TwbSignature = 'IMOD';
  IMPF : TwbSignature = 'IMPF';
  IMPS : TwbSignature = 'IMPS';
  IMSP : TwbSignature = 'IMSP'; { New to Skyrim }
  INAM : TwbSignature = 'INAM';
  INCC : TwbSignature = 'INCC'; { New to Skyrim }
  INDX : TwbSignature = 'INDX';
  INFC : TwbSignature = 'INFC';
  INFO : TwbSignature = 'INFO';
  INFX : TwbSignature = 'INFX';
  INGR : TwbSignature = 'INGR';
  INNR : TwbSignature = 'INNR'; { New To Fallout 4 }
  INOA : TwbSignature = 'INOA'; { xEdit internal use only }
  INOM : TwbSignature = 'INOM'; { xEdit internal use only }
  INRD : TwbSignature = 'INRD'; { New To Fallout 4 }
  INRF : TwbSignature = 'INRF'; { New To Fallout 76 }
  INTM : TwbSignature = 'INTM';
  INTT : TwbSignature = 'INTT'; { New To Fallout 4 }
  INTV : TwbSignature = 'INTV';
  IOVR : TwbSignature = 'IOVR'; { New To Fallout 4 }
  IPCT : TwbSignature = 'IPCT';
  IPDS : TwbSignature = 'IPDS';
  IRES : TwbSignature = 'IRES'; { New To Starfield }
  IRON : TwbSignature = 'IRON';
  ISET : TwbSignature = 'ISET'; { New To Starfield }
  ISIZ : TwbSignature = 'ISIZ'; { New To Fallout 4 }
  ISTX : TwbSignature = 'ISTX'; { New To Starfield }
  ITID : TwbSignature = 'ITID'; { New To Fallout 4 }
  ITMC : TwbSignature = 'ITMC'; { New To Fallout 4 }
  ITME : TwbSignature = 'ITME'; { New To Fallout 4 }
  ITMS : TwbSignature = 'ITMS'; { New To Fallout 4 }
  ITXT : TwbSignature = 'ITXT';
  J0TX : TwbSignature = 'J0TX';
  JAIL : TwbSignature = 'JAIL'; { New To Skyrim }
  JASF : TwbSignature = 'JASF'; { New To Fallout 76 }
  JCOL : TwbSignature = 'JCOL'; { New To Starfield }
  JNAM : TwbSignature = 'JNAM';
  JOUT : TwbSignature = 'JOUT'; { New To Skyrim }
  K0TX : TwbSignature = 'K0TX';
  KEYM : TwbSignature = 'KEYM';
  KFFZ : TwbSignature = 'KFFZ';
  KILL : TwbSignature = 'KILL';
  KNAM : TwbSignature = 'KNAM';
  KSIZ : TwbSignature = 'KSIZ';
  KSSM : TwbSignature = 'KSSM'; { New To Fallout 4 }
  KWDA : TwbSignature = 'KWDA';
  KYWD : TwbSignature = 'KYWD';
  L0TX : TwbSignature = 'L0TX';
  LAMN : TwbSignature = 'LAMN'; { New To Fallout 76 }
  LAMX : TwbSignature = 'LAMX'; { New To Fallout 76 }
  LAND : TwbSignature = 'LAND';
  LAVT : TwbSignature = 'LAVT'; { New To Fallout 76 }
  LAYR : TwbSignature = 'LAYR'; { New to Fallout 4 }
  LCEC : TwbSignature = 'LCEC'; { New to Skyrim }
  LCEP : TwbSignature = 'LCEP'; { New to Skyrim }
  LCID : TwbSignature = 'LCID'; { New to Skyrim }
  LCLD : TwbSignature = 'LCLD';
  LCPG : TwbSignature = 'LCPG';
  LCPR : TwbSignature = 'LCPR'; { New to Skyrim }
  LCRT : TwbSignature = 'LCRT';
  LCSR : TwbSignature = 'LCSR'; { New to Skyrim }
  LCTN : TwbSignature = 'LCTN';
  LCUN : TwbSignature = 'LCUN'; { New to Skyrim }
  LCUR : TwbSignature = 'LCUR'; { New To Starfield }
  LENS : TwbSignature = 'LENS'; { New to Fallout 4 }
  LEPC : TwbSignature = 'LEPC'; { New to Fallout 4 }
  LEVL : TwbSignature = 'LEVL';
  LFSD : TwbSignature = 'LFSD'; { New to Fallout 4 }
  LFSP : TwbSignature = 'LFSP'; { New to Fallout 4 }
  LGDI : TwbSignature = 'LGDI'; { New To Fallout 76 }
  LGTM : TwbSignature = 'LGTM';
  LIGH : TwbSignature = 'LIGH';
  LILS : TwbSignature = 'LILS'; { New To Fallout 76 }
  LIMC : TwbSignature = 'LIMC'; { New To Fallout 76 }
  LINV : TwbSignature = 'LINV'; { New To Fallout 76 }
  LIPC : TwbSignature = 'LIPC'; { New To Fallout 76 }
  LLCT : TwbSignature = 'LLCT'; { New to Skyrim, part of LVLI 'Count' }
  LLKC : TwbSignature = 'LLKC'; { New to Fallout 4 }
  LLLD : TwbSignature = 'LLLD'; { New To Starfield }
  LLRB : TwbSignature = 'LLRB'; { New To Starfield }
  LLRV : TwbSignature = 'LLRV'; { New To Starfield }
  LLSH : TwbSignature = 'LLSH'; { New To Starfield }
  LLVL : TwbSignature = 'LLVL'; { New To Fallout 76 }
  LMSW : TwbSignature = 'LMSW'; { New To Starfield }
  LNA2 : TwbSignature = 'LNA2'; { New To Starfield }
  LNAM : TwbSignature = 'LNAM';
  LOCK : TwbSignature = 'LOCK';
  LODB : TwbSignature = 'LODB'; { New To Starfield }
  LODP : TwbSignature = 'LODP'; { New To Fallout 76 }
  LOUT : TwbSignature = 'LOUT'; { New To Fallout 76 }
  LRNC : TwbSignature = 'LRNC'; { New to Fallout 76 }
  LRNM : TwbSignature = 'LRNM'; { New to Fallout 76 }
  LSCR : TwbSignature = 'LSCR';
  LSCT : TwbSignature = 'LSCT';
  LSPC : TwbSignature = 'LSPC'; { New to Fallout 76 }
  LSPR : TwbSignature = 'LSPR'; { New to Fallout 4 }
  LSST : TwbSignature = 'LSST'; { New to Fallout 76 }
  LTEX : TwbSignature = 'LTEX';
  LTMP : TwbSignature = 'LTMP';
  LTPC : TwbSignature = 'LTPC'; { New to Fallout 4 }
  LTPT : TwbSignature = 'LTPT'; { New to Fallout 4 }
  LVCL : TwbSignature = 'LVCL'; { New To Fallout 76 }
  LVCR : TwbSignature = 'LVCR'; { New To Starfield }
  LVCT : TwbSignature = 'LVCT'; { New To Fallout 76 }
  LVCV : TwbSignature = 'LVCV'; { New To Fallout 76 }
  LVIG : TwbSignature = 'LVIG'; { New To Fallout 76 }
  LVIT : TwbSignature = 'LVIT'; { New To Fallout 76 }
  LVIV : TwbSignature = 'LVIV'; { New To Fallout 76 }
  LVLB : TwbSignature = 'LVLB'; { New To Starfield }
  LVLC : TwbSignature = 'LVLC';
  LVLD : TwbSignature = 'LVLD';
  LVLF : TwbSignature = 'LVLF';
  LVLG : TwbSignature = 'LVLG';
  LVLI : TwbSignature = 'LVLI';
  LVLL : TwbSignature = 'LVLL'; { New To Starfield }
  LVLM : TwbSignature = 'LVLM'; { New to Fallout 4 }
  LVLN : TwbSignature = 'LVLN';
  LVLO : TwbSignature = 'LVLO';
  LVLP : TwbSignature = 'LVLP'; { New To Fallout 76 }
  LVLT : TwbSignature = 'LVLT'; { New To Fallout 76 }
  LVLV : TwbSignature = 'LVLV'; { New To Fallout 76 }
  LVMG : TwbSignature = 'LVMG'; { New To Fallout 76 }
  LVMT : TwbSignature = 'LVMT'; { New To Fallout 76 }
  LVMV : TwbSignature = 'LVMV'; { New To Fallout 76 }
  LVOC : TwbSignature = 'LVOC'; { New To Fallout 76 }
  LVOG : TwbSignature = 'LVOG'; { New To Fallout 76 }
  LVOT : TwbSignature = 'LVOT'; { New To Fallout 76 }
  LVOV : TwbSignature = 'LVOV'; { New To Fallout 76 }
  LVPC : TwbSignature = 'LVPC'; { New To Fallout 76 }
  LVSC : TwbSignature = 'LVSC'; { New To Starfield }
  LVSG : TwbSignature = 'LVSG'; { New to Fallout 4 }
  LVSP : TwbSignature = 'LVSP';
  LVUD : TwbSignature = 'LVUD'; { New To Fallout 76 }
  LVUO : TwbSignature = 'LVUO'; { New To Fallout 76 }
  M0TX : TwbSignature = 'M0TX';
  MAAM : TwbSignature = 'MAAM'; { New To Starfield }
  MAGA : TwbSignature = 'MAGA'; { New To Fallout 76 }
  MAGF : TwbSignature = 'MAGF'; { New To Fallout 76 }
  MAGG : TwbSignature = 'MAGG'; { New To Fallout 76 }
  MASE : TwbSignature = 'MASE'; { New To Fallout 4 }
  MAST : TwbSignature = 'MAST';
  MATO : TwbSignature = 'MATO';
  MATT : TwbSignature = 'MATT';
  MBNR : TwbSignature = 'MBNR'; { New To Fallout 76 }
  MCHT : TwbSignature = 'MCHT'; { New to Skyrim }
  MCQP : TwbSignature = 'MCQP'; { New To Fallout 76 }
  MDOB : TwbSignature = 'MDOB';
  MDSP : TwbSignature = 'MDSP'; { New to Fallout 76 }
  MESG : TwbSignature = 'MESG';
  MGEF : TwbSignature = 'MGEF';
  MHDT : TwbSignature = 'MHDT'; { New to Skyrim }
  MIC2 : TwbSignature = 'MIC2';
  MICN : TwbSignature = 'MICN'; { New to Fallout 4 }
  MICO : TwbSignature = 'MICO';
  MIID : TwbSignature = 'MIID'; { New To Fallout 76 }
  MISC : TwbSignature = 'MISC';
  MISI : TwbSignature = 'MISI'; { New to Fallout 76. Found in EXE GRUP order }
  MLM1 : TwbSignature = 'MLM1'; { New To Starfield }
  MLM2 : TwbSignature = 'MLM2'; { New To Starfield }
  MLM3 : TwbSignature = 'MLM3'; { New To Starfield }
  MLM4 : TwbSignature = 'MLM4'; { New To Starfield }
  MLM5 : TwbSignature = 'MLM5'; { New To Starfield }
  MLM6 : TwbSignature = 'MLM6'; { New To Starfield }
  MLSI : TwbSignature = 'MLSI'; { New to Fallout 4 }
  MMRK : TwbSignature = 'MMRK';
  MMSB : TwbSignature = 'MMSB'; { New to Fallout 76 NW. }
  MNAM : TwbSignature = 'MNAM';
  MO2B : TwbSignature = 'MO2B';
  MO2C : TwbSignature = 'MO2C'; { New to Fallout 4 }
  MO2F : TwbSignature = 'MO2F'; { New to Fallout 4 }
  MO2S : TwbSignature = 'MO2S';
  MO2T : TwbSignature = 'MO2T';
  MO3B : TwbSignature = 'MO3B';
  MO3C : TwbSignature = 'MO3C'; { New to Fallout 4 }
  MO3F : TwbSignature = 'MO3F'; { New to Fallout 4 }
  MO3S : TwbSignature = 'MO3S';
  MO3T : TwbSignature = 'MO3T';
  MO4B : TwbSignature = 'MO4B';
  MO4C : TwbSignature = 'MO4C'; { New to Fallout 4 }
  MO4F : TwbSignature = 'MO4F'; { New to Fallout 4 }
  MO4S : TwbSignature = 'MO4S';
  MO4T : TwbSignature = 'MO4T';
  MO5C : TwbSignature = 'MO5C'; { New to Fallout 4 }
  MO5F : TwbSignature = 'MO5F'; { New to Fallout 4 }
  MO5S : TwbSignature = 'MO5S'; { New to Skyrim }
  MO5T : TwbSignature = 'MO5T'; { New to Skyrim }
  MO6F : TwbSignature = 'MO6F'; { New To Starfield }
  MO6T : TwbSignature = 'MO6T'; { New to Starfield }
  MO7F : TwbSignature = 'MO7F'; { New To Starfield }
  MO7T : TwbSignature = 'MO7T'; { New to Starfield }
  MOBC : TwbSignature = 'MOBC'; { New To Starfield }
  MOD2 : TwbSignature = 'MOD2';
  MOD3 : TwbSignature = 'MOD3';
  MOD4 : TwbSignature = 'MOD4';
  MOD5 : TwbSignature = 'MOD5'; { New to Skyrim }
  MOD6 : TwbSignature = 'MOD6'; { New to Starfield }
  MOD7 : TwbSignature = 'MOD7'; { New to Starfield }
  MODB : TwbSignature = 'MODB';
  MODC : TwbSignature = 'MODC'; { New to Fallout 4 }
  MODD : TwbSignature = 'MODD'; { New to Fallout 76 }
  MODF : TwbSignature = 'MODF'; { New to Fallout 4 }
  MODL : TwbSignature = 'MODL';
  MODQ : TwbSignature = 'MODQ'; { New to Fallout 4 }
  MODS : TwbSignature = 'MODS';
  MODT : TwbSignature = 'MODT';
  MOLM : TwbSignature = 'MOLM'; { New To Starfield }
  MOSD : TwbSignature = 'MOSD';
  MOVT : TwbSignature = 'MOVT';
  MPAI : TwbSignature = 'MPAI'; { New To Skyrim }
  MPAV : TwbSignature = 'MPAV'; { New To Skyrim }
  MPCD : TwbSignature = 'MPCD'; { New to Fallout 4 }
  MPGM : TwbSignature = 'MPGM'; { New To Starfield }
  MPGN : TwbSignature = 'MPGN'; { New to Fallout 4 }
  MPGS : TwbSignature = 'MPGS'; { New to Fallout 4 }
  MPPC : TwbSignature = 'MPPC'; { New to Fallout 4 }
  MPPF : TwbSignature = 'MPPF'; { New to Fallout 4 }
  MPPI : TwbSignature = 'MPPI'; { New to Fallout 4 }
  MPPK : TwbSignature = 'MPPK'; { New to Fallout 4 }
  MPPM : TwbSignature = 'MPPM'; { New to Fallout 4 }
  MPPN : TwbSignature = 'MPPN'; { New to Fallout 4 }
  MPPT : TwbSignature = 'MPPT'; { New to Fallout 4 }
  MPRT : TwbSignature = 'MPRT'; { New to Skyrim }
  MRPH : TwbSignature = 'MRPH'; { New To Starfield }
  MRSV : TwbSignature = 'MRSV'; { New to Fallout 4 }
  MSCS : TwbSignature = 'MSCS'; { New To Fallout 76 }
  MSDK : TwbSignature = 'MSDK'; { New to Fallout 4 }
  MSDV : TwbSignature = 'MSDV'; { New to Fallout 4 }
  MSET : TwbSignature = 'MSET';
  MSID : TwbSignature = 'MSID'; { New to Fallout 4 }
  MSLS : TwbSignature = 'MSLS'; { New To Starfield }
  MSM0 : TwbSignature = 'MSM0'; { New to Fallout 4 }
  MSM1 : TwbSignature = 'MSM1'; { New to Fallout 4 }
  MSMO : TwbSignature = 'MSMO'; { New To Starfield }
  MSSA : TwbSignature = 'MSSA'; { New To Starfield }
  MSSI : TwbSignature = 'MSSI'; { New To Starfield }
  MSSS : TwbSignature = 'MSSS'; { New To Starfield }
  MSTF : TwbSignature = 'MSTF'; { New To Starfield }
  MSTT : TwbSignature = 'MSTT';
  MSWP : TwbSignature = 'MSWP'; { New to Fallout 4 }
  MTNM : TwbSignature = 'MTNM'; { New to Skyrim }
  MTPT : TwbSignature = 'MTPT'; { New To Starfield }
  MTSH : TwbSignature = 'MTSH'; { New To Starfield }
  MTYP : TwbSignature = 'MTYP'; { New To Skyrim }
  MUID : TwbSignature = 'MUID'; { New To Starfield }
  MUSC : TwbSignature = 'MUSC';
  MUST : TwbSignature = 'MUST';
  MWD1 : TwbSignature = 'MWD1';
  MWD2 : TwbSignature = 'MWD2';
  MWD3 : TwbSignature = 'MWD3';
  MWD4 : TwbSignature = 'MWD4';
  MWD5 : TwbSignature = 'MWD5';
  MWD6 : TwbSignature = 'MWD6';
  MWD7 : TwbSignature = 'MWD7';
  MWGT : TwbSignature = 'MWGT'; { New to Fallout 4 }
  MXCT : TwbSignature = 'MXCT'; { New To Fallout 76 }
  N0TX : TwbSignature = 'N0TX';
  NAM0 : TwbSignature = 'NAM0';
  NAM1 : TwbSignature = 'NAM1';
  NAM2 : TwbSignature = 'NAM2';
  NAM3 : TwbSignature = 'NAM3';
  NAM4 : TwbSignature = 'NAM4';
  NAM5 : TwbSignature = 'NAM5';
  NAM6 : TwbSignature = 'NAM6';
  NAM7 : TwbSignature = 'NAM7';
  NAM8 : TwbSignature = 'NAM8';
  NAM9 : TwbSignature = 'NAM9';
  NAMA : TwbSignature = 'NAMA'; { New to Skyrim }
  NAME : TwbSignature = 'NAME';
  NAVH : TwbSignature = 'NAVH'; { New To Fallout 76 }
  NAVI : TwbSignature = 'NAVI';
  NAVM : TwbSignature = 'NAVM';
  NETO : TwbSignature = 'NETO'; { New to Fallout 4 }
  NEXT : TwbSignature = 'NEXT';
  NIFT : TwbSignature = 'NIFT';
  NIFZ : TwbSignature = 'NIFZ';
  NLDT : TwbSignature = 'NLDT'; { New To Starfield }
  NNAM : TwbSignature = 'NNAM';
  NNGS : TwbSignature = 'NNGS'; { New to Fallout 4 }
  NNGT : TwbSignature = 'NNGT'; { New to Fallout 4 }
  NNUS : TwbSignature = 'NNUS'; { New to Fallout 4 }
  NNUT : TwbSignature = 'NNUT'; { New to Fallout 4 }
  NOCM : TwbSignature = 'NOCM'; { New to Fallout 4 }
  NONE : TwbSignature = 'NONE'; { New to Fallout 4, used in OMOD Form Type }
  NOTE : TwbSignature = 'NOTE'; { New to Fallout 4 }
  NPC_ : TwbSignature = 'NPC_';
  NPOS : TwbSignature = 'NPOS'; { New to Fallout 4 }
  NPOT : TwbSignature = 'NPOT'; { New to Fallout 4 }
  NQUS : TwbSignature = 'NQUS'; { New to Fallout 4 }
  NQUT : TwbSignature = 'NQUT'; { New to Fallout 4 }
  NTOP : TwbSignature = 'NTOP'; { New to Fallout 4 }
  NTRM : TwbSignature = 'NTRM'; { New to Fallout 4 }
  NTWK : TwbSignature = 'NTWK'; { New To Fallout 76 }
  NULL : TwbSignature = 'NULL';
  NVCA : TwbSignature = 'NVCA';
  NVCI : TwbSignature = 'NVCI';
  NVDP : TwbSignature = 'NVDP';
  NVER : TwbSignature = 'NVER';
  NVEX : TwbSignature = 'NVEX';
  NVGD : TwbSignature = 'NVGD';
  NVMI : TwbSignature = 'NVMI';
  NVNM : TwbSignature = 'NVNM'; { New to Skyrim }
  NVPE : TwbSignature = 'NVPE';
  NVPP : TwbSignature = 'NVPP'; { New to Skyrim }
  NVSI : TwbSignature = 'NVSI'; { New to Dawnguard }
  NVTR : TwbSignature = 'NVTR';
  NVVX : TwbSignature = 'NVVX';
  O0TX : TwbSignature = 'O0TX';
  OAAT : TwbSignature = 'OAAT';
  OBND : TwbSignature = 'OBND';
  OBST : TwbSignature = 'OBST'; { New to Fallout 76 }
  OBSV : TwbSignature = 'OBSV'; { New To Starfield }
  OBTE : TwbSignature = 'OBTE'; { New to Fallout 4 }
  OBTF : TwbSignature = 'OBTF'; { New to Fallout 4 }
  OBTS : TwbSignature = 'OBTS'; { New to Fallout 4 }
  OCCV : TwbSignature = 'OCCV'; { New To Starfield }
  OCOR : TwbSignature = 'OCOR'; { New to Skyrim }
  ODTY : TwbSignature = 'ODTY'; { New To Starfield }
  OFST : TwbSignature = 'OFST';
  OMOD : TwbSignature = 'OMOD'; { New to Fallout 4 }
  ONA2 : TwbSignature = 'ONA2'; { New To Starfield }
  ONAM : TwbSignature = 'ONAM';
  OPDS : TwbSignature = 'OPDS'; { New To Fallout 76 }
  OSWP : TwbSignature = 'OSWP'; { New To Starfield }
  OTFT : TwbSignature = 'OTFT';
  OVIS : TwbSignature = 'OVIS'; { New to Fallout 4 }
  PACH : TwbSignature = 'PACH'; { New To Fallout 76 }
  PACK : TwbSignature = 'PACK';
  PAEQ : TwbSignature = 'PAEQ'; { New To Fallout 76 }
  PAHD : TwbSignature = 'PAHD'; { New To Fallout 76 }
  PAPI : TwbSignature = 'PAPI'; { New To Starfield }
  PAPN : TwbSignature = 'PAPN'; { New To Starfield }
  PAQO : TwbSignature = 'PAQO'; { New To Starfield }
  PARW : TwbSignature = 'PARW'; { New to Skyrim }
  PASP : TwbSignature = 'PASP'; { New To Starfield }
  PBAR : TwbSignature = 'PBAR'; { New to Skyrim }
  PBEA : TwbSignature = 'PBEA'; { New to Skyrim }
  PBLT : TwbSignature = 'PBLT'; { New To Fallout 76 0.2.838.0 }
  PBRT : TwbSignature = 'PBRT'; { New To Fallout 76 0.2.838.0 }
  PCBN : TwbSignature = 'PCBN'; { New To Starfield }
  PCCB : TwbSignature = 'PCCB'; { New To Starfield }
  PCCC : TwbSignature = 'PCCC'; { New To Starfield }
  PCCN : TwbSignature = 'PCCN'; { New To Starfield }
  PCDP : TwbSignature = 'PCDP'; { New To Fallout 76 }
  PCDV : TwbSignature = 'PCDV'; { New To Fallout 76 }
  PCEN : TwbSignature = 'PCEN'; { New To Fallout 76 }
  PCMB : TwbSignature = 'PCMB'; { New to Fallout 4 }
  PCMT : TwbSignature = 'PCMT'; { New To Starfield }
  PCON : TwbSignature = 'PCON'; { New to Skyrim }
  PCRD : TwbSignature = 'PCRD'; { New To Fallout 76 }
  PDCL : TwbSignature = 'PDCL'; { New To Starfield }
  PDSH : TwbSignature = 'PDSH'; { New To Starfield }
  PDTO : TwbSignature = 'PDTO'; { New to Skyrim }
  PEDF : TwbSignature = 'PEDF'; { New To Fallout 76 }
  PEPF : TwbSignature = 'PEPF'; { New To Fallout 76 0.2.782.0 }
  PEPI : TwbSignature = 'PEPI'; { New To Fallout 76 }
  PERK : TwbSignature = 'PERK';
  PERM : TwbSignature = 'PERM'; { New To Fallout 76 }
  PERS : TwbSignature = 'PERS'; { New To Starfield }
  PERT : TwbSignature = 'PERT'; { New To Fallout 76 }
  PEWI : TwbSignature = 'PEWI'; { New To Fallout 76 0.2.782.0 }
  PEWR : TwbSignature = 'PEWR'; { New To Fallout 76 0.2.782.0 }
  PFAC : TwbSignature = 'PFAC'; { New To Fallout 76 }
  PFHS : TwbSignature = 'PFHS'; { New To Starfield }
  PFIG : TwbSignature = 'PFIG';
  PFIN : TwbSignature = 'PFIN';
  PFLA : TwbSignature = 'PFLA'; { New to Skyrim }
  PFO2 : TwbSignature = 'PFO2'; { New to Skyrim }
  PFOR : TwbSignature = 'PFOR'; { New to Skyrim }
  PFPC : TwbSignature = 'PFPC';
  PFRN : TwbSignature = 'PFRN'; { New to Fallout 4 }
  PGAG : TwbSignature = 'PGAG';
  PGRE : TwbSignature = 'PGRE';
  PGRI : TwbSignature = 'PGRI';
  PGRL : TwbSignature = 'PGRL';
  PGRP : TwbSignature = 'PGRP';
  PGRR : TwbSignature = 'PGRR';
  PHLA : TwbSignature = 'PHLA'; { New To Starfield }
  PHST : TwbSignature = 'PHST'; { New To Fallout 76 }
  PHTN : TwbSignature = 'PHTN'; { New to Skyrim }
  PHWT : TwbSignature = 'PHWT'; { New to Skyrim }
  PHZD : TwbSignature = 'PHZD';
  PKAM : TwbSignature = 'PKAM';
  PKC2 : TwbSignature = 'PKC2'; { New to Skyrim }
  PKCU : TwbSignature = 'PKCU'; { New to Skyrim }
  PKDD : TwbSignature = 'PKDD';
  PKDT : TwbSignature = 'PKDT';
  PKE2 : TwbSignature = 'PKE2';
  PKED : TwbSignature = 'PKED';
  PKFD : TwbSignature = 'PKFD';
  PKID : TwbSignature = 'PKID';
  PKIN : TwbSignature = 'PKIN'; { New to Fallout 4 }
  PKPT : TwbSignature = 'PKPT';
  PKW3 : TwbSignature = 'PKW3';
  PLCN : TwbSignature = 'PLCN'; { New to Skyrim }
  PLD2 : TwbSignature = 'PLD2';
  PLDT : TwbSignature = 'PLDT';
  PLRL : TwbSignature = 'PLRL'; { New To Starfield }
  PLVD : TwbSignature = 'PLVD'; { New to Skyrim }
  PLYR : TwbSignature = 'PLYR';
  PMFT : TwbSignature = 'PMFT'; { New To Fallout 76 }
  PMIS : TwbSignature = 'PMIS';
  PNAM : TwbSignature = 'PNAM';
  PNDT : TwbSignature = 'PNDT'; { New To Starfield }
  PNST : TwbSignature = 'PNST'; { New To Starfield }
  POBA : TwbSignature = 'POBA';
  POCA : TwbSignature = 'POCA';
  POEA : TwbSignature = 'POEA';
  PPAD : TwbSignature = 'PPAD'; { New To Fallout 76 }
  PPAK : TwbSignature = 'PPAK'; { New To Fallout 76 }
  PPBD : TwbSignature = 'PPBD'; { New To Starfield }
  PPCL : TwbSignature = 'PPCL'; { New To Fallout 76 }
  PPFC : TwbSignature = 'PPFC'; { New To Fallout 76 }
  PPLO : TwbSignature = 'PPLO'; { New To Fallout 76 }
  PPRL : TwbSignature = 'PPRL'; { New To Fallout 76 }
  PPST : TwbSignature = 'PPST'; { New To Starfield }
  PRAS : TwbSignature = 'PRAS'; { New To Starfield }
  PRCB : TwbSignature = 'PRCB'; { New to Skyrim }
  PRCS : TwbSignature = 'PRCS'; { New To Starfield }
  PRDS : TwbSignature = 'PRDS'; { New To Starfield }
  PRFI : TwbSignature = 'PRFI'; { New To Fallout 76 }
  PRFS : TwbSignature = 'PRFS'; { New To Fallout 76 }
  PRFV : TwbSignature = 'PRFV';
  PRIS : TwbSignature = 'PRIS'; { New To Starfield }
  PRKC : TwbSignature = 'PRKC';
  PRKE : TwbSignature = 'PRKE';
  PRKF : TwbSignature = 'PRKF';
  PRKR : TwbSignature = 'PRKR'; { New to Skyrim }
  PRKZ : TwbSignature = 'PRKZ'; { New to Skyrim }
  PROD : TwbSignature = 'PROD'; { New To Starfield }
  PROJ : TwbSignature = 'PROJ';
  PRON : TwbSignature = 'PRON'; { New To Starfield }
  PRPS : TwbSignature = 'PRPS'; { New to Fallout 4 }
  PRRF : TwbSignature = 'PRRF'; { New To Starfield }
  PRRK : TwbSignature = 'PRRK'; { New To Starfield }
  PSDC : TwbSignature = 'PSDC'; { New To Starfield }
  PSDF : TwbSignature = 'PSDF'; { New To Starfield }
  PSDT : TwbSignature = 'PSDT';
  PTCL : TwbSignature = 'PTCL'; { New To Starfield }
  PTD2 : TwbSignature = 'PTD2';
  PTDA : TwbSignature = 'PTDA'; { New to Skyrim }
  PTDT : TwbSignature = 'PTDT';
  PTOP : TwbSignature = 'PTOP'; { New to Fallout 4 }
  PTRN : TwbSignature = 'PTRN'; { New to Fallout 4 }
  PTST : TwbSignature = 'PTST'; { New To Starfield }
  PTT2 : TwbSignature = 'PTT2'; { New To Starfield }
  PUID : TwbSignature = 'PUID';
  PUSH : TwbSignature = 'PUSH'; { New To Starfield }
  PWAT : TwbSignature = 'PWAT';
  QARF : TwbSignature = 'QARF'; { New to Fallout 76 1.2.2.1 }
  QARV : TwbSignature = 'QARV'; { New to Fallout 76 1.2.2.1 }
  QECV : TwbSignature = 'QECV'; { New To Fallout 76 }
  QETE : TwbSignature = 'QETE'; { New To Fallout 76 }
  QETL : TwbSignature = 'QETL'; { New To Fallout 76 }
  QMAD : TwbSignature = 'QMAD'; { New To Fallout 76 }
  QMAI : TwbSignature = 'QMAI'; { New To Fallout 76 }
  QMAO : TwbSignature = 'QMAO'; { New To Fallout 76 }
  QMCI : TwbSignature = 'QMCI'; { New To Fallout 76 }
  QMDE : TwbSignature = 'QMDE'; { New To Fallout 76 }
  QMDI : TwbSignature = 'QMDI'; { New To Fallout 76 }
  QMDL : TwbSignature = 'QMDL'; { New To Fallout 76 }
  QMDN : TwbSignature = 'QMDN'; { New To Fallout 76 }
  QMDP : TwbSignature = 'QMDP'; { New To Fallout 76 }
  QMDQ : TwbSignature = 'QMDQ'; { New To Fallout 76 }
  QMDS : TwbSignature = 'QMDS'; { New To Starfield }
  QMDT : TwbSignature = 'QMDT'; { New To Fallout 76 }
  QMOD : TwbSignature = 'QMOD'; { New To Fallout 76 }
  QMOI : TwbSignature = 'QMOI'; { New To Fallout 76 }
  QMOT : TwbSignature = 'QMOT'; { New To Fallout 76 }
  QMPO : TwbSignature = 'QMPO'; { New To Fallout 76 }
  QMSD : TwbSignature = 'QMSD'; { New To Fallout 76 }
  QMSI : TwbSignature = 'QMSI'; { New To Fallout 76 }
  QMSO : TwbSignature = 'QMSO'; { New To Fallout 76 }
  QMSU : TwbSignature = 'QMSU'; { New To Starfield }
  QMTR : TwbSignature = 'QMTR'; { New To Fallout 76 }
  QMTT : TwbSignature = 'QMTT'; { New To Fallout 76 }
  QMTY : TwbSignature = 'QMTY'; { New To Starfield }
  QNAM : TwbSignature = 'QNAM';
  QOBJ : TwbSignature = 'QOBJ';
  QOTM : TwbSignature = 'QOTM'; { New To Fallout 76 }
  QPMT : TwbSignature = 'QPMT';
  QQSD : TwbSignature = 'QQSD'; { New To Fallout 76 }
  QQSK : TwbSignature = 'QQSK'; { New To Fallout 76 }
  QQSV : TwbSignature = 'QQSV'; { New To Fallout 76 }
  QRCO : TwbSignature = 'QRCO'; { New To Fallout 76 }
  QRCR : TwbSignature = 'QRCR'; { New To Starfield }
  QRCX : TwbSignature = 'QRCX'; { New To Fallout 76 }
  QRLI : TwbSignature = 'QRLI'; { New To Fallout 76 }
  QRLR : TwbSignature = 'QRLR'; { New To Fallout 76 }
  QRRD : TwbSignature = 'QRRD'; { New To Starfield }
  QRRI : TwbSignature = 'QRRI'; { New To Fallout 76 }
  QRWD : TwbSignature = 'QRWD'; { New To Fallout 76 0.2.782.0 }
  QRWT : TwbSignature = 'QRWT'; { New To Fallout 76 }
  QRXP : TwbSignature = 'QRXP'; { New To Starfield }
  QSDD : TwbSignature = 'QSDD'; { New To Fallout 76 }
  QSDT : TwbSignature = 'QSDT';
  QSLC : TwbSignature = 'QSLC'; { New To Fallout 76 }
  QSRC : TwbSignature = 'QSRC'; { New To Starfield }
  QSRD : TwbSignature = 'QSRD'; { New To Fallout 76 }
  QSSK : TwbSignature = 'QSSK'; { New To Fallout 76 }
  QSTA : TwbSignature = 'QSTA';
  QSTI : TwbSignature = 'QSTI'; { New to Fallout 4 }
  QSTR : TwbSignature = 'QSTR';
  QTFS : TwbSignature = 'QTFS'; { New To Fallout 76 }
  QTGL : TwbSignature = 'QTGL'; { New To Skyrim }
  QTLM : TwbSignature = 'QTLM'; { New To Fallout 76 }
  QTOP : TwbSignature = 'QTOP'; { New to Fallout 4 }
  QTVR : TwbSignature = 'QTVR'; { New To Fallout 76 }
  QTYP : TwbSignature = 'QTYP'; { New To Starfield }
  QUAL : TwbSignature = 'QUAL'; { New To Skyrim }
  QUIM : TwbSignature = 'QUIM'; { New To Fallout 76 }
  QUST : TwbSignature = 'QUST';
  RABG : TwbSignature = 'RABG'; { New To Starfield }
  RACE : TwbSignature = 'RACE';
  RADR : TwbSignature = 'RADR'; { New To Fallout 4 }
  RADS : TwbSignature = 'RADS';
  RAFB : TwbSignature = 'RAFB';
  RAFD : TwbSignature = 'RAFD';
  RAGA : TwbSignature = 'RAGA';
  RAPS : TwbSignature = 'RAPS';
  RBPC : TwbSignature = 'RBPC'; { New To Fallout 4 }
  RCBN : TwbSignature = 'RCBN'; { New To Fallout 76 }
  RCCT : TwbSignature = 'RCCT';
  RCEC : TwbSignature = 'RCEC'; { New To Skyrim }
  RCIL : TwbSignature = 'RCIL';
  RCLR : TwbSignature = 'RCLR';
  RCND : TwbSignature = 'RCND'; { New To Fallout 76 }
  RCOD : TwbSignature = 'RCOD';
  RCPE : TwbSignature = 'RCPE';
  RCPR : TwbSignature = 'RCPR'; { New to Dawnguard }
  RCQY : TwbSignature = 'RCQY';
  RCSR : TwbSignature = 'RCSR'; { New To Skyrim }
  RCUN : TwbSignature = 'RCUN'; { New To Skyrim }
  RCUR : TwbSignature = 'RCUR'; { New To Starfield }
  RDAT : TwbSignature = 'RDAT';
  RDES : TwbSignature = 'RDES'; { New To Fallout 76 }
  RDGS : TwbSignature = 'RDGS';
  RDID : TwbSignature = 'RDID';
  RDIF : TwbSignature = 'RDIF'; { New To Starfield }
  RDMD : TwbSignature = 'RDMD';
  RDMO : TwbSignature = 'RDMO';
  RDMP : TwbSignature = 'RDMP';
  RDOT : TwbSignature = 'RDOT';
  RDSA : TwbSignature = 'RDSA'; { New to Skyrim }
  RDSB : TwbSignature = 'RDSB';
  RDSD : TwbSignature = 'RDSD';
  RDSI : TwbSignature = 'RDSI';
  RDSN : TwbSignature = 'RDSN'; { New to Fallout 76 }
  RDWK : TwbSignature = 'RDWK'; { New to Fallout 76 }
  RDWT : TwbSignature = 'RDWT';
  RECF : TwbSignature = 'RECF'; { New to Fallout 76 }
  REFL : TwbSignature = 'REFL'; { New To Starfield }
  REFR : TwbSignature = 'REFR';
  REGN : TwbSignature = 'REGN';
  RELA : TwbSignature = 'RELA';
  REMP : TwbSignature = 'REMP';
  RENT : TwbSignature = 'RENT'; { New To Fallout 76 }
  REPL : TwbSignature = 'REPL';
  REPM : TwbSignature = 'REPM'; { New to Fallout 76 }
  REPR : TwbSignature = 'REPR'; { New To Fallout 76 }
  REPT : TwbSignature = 'REPT'; { New To Fallout 4 }
  REPU : TwbSignature = 'REPU';
  RESN : TwbSignature = 'RESN'; { New To Starfield }
  RESO : TwbSignature = 'RESO'; { New To Fallout 76 }
  REVB : TwbSignature = 'REVB';
  RFCT : TwbSignature = 'RFCT';
  RFDP : TwbSignature = 'RFDP'; { New To Starfield }
  RFGP : TwbSignature = 'RFGP'; { New to Fallout 4 }
  RGDL : TwbSignature = 'RGDL'; { Unused in Skyrim, but contained in Skyrim.esm }
  RGW2 : TwbSignature = 'RGW2'; { New To Fallout 76 }
  RGW3 : TwbSignature = 'RGW3'; { New To Fallout 76 }
  RLBC : TwbSignature = 'RLBC'; { New To Fallout 76 }
  RLDM : TwbSignature = 'RLDM'; { New to Fallout 4 }
  RNAM : TwbSignature = 'RNAM';
  RNMV : TwbSignature = 'RNMV'; { New to Skyrim }
  RPLD : TwbSignature = 'RPLD';
  RPLI : TwbSignature = 'RPLI';
  RPRF : TwbSignature = 'RPRF'; { New To Skyrim }
  RPRM : TwbSignature = 'RPRM'; { New To Skyrim }
  RQPK : TwbSignature = 'RQPK'; { New To Starfield }
  RSCS : TwbSignature = 'RSCS'; { New To Starfield }
  RSGD : TwbSignature = 'RSGD'; { New To Starfield }
  RSMC : TwbSignature = 'RSMC'; { New To Starfield }
  RSMH : TwbSignature = 'RSMH'; { New To Starfield }
  RSPJ : TwbSignature = 'RSPJ'; { New To Starfield }
  RVIS : TwbSignature = 'RVIS'; { New to Fallout 4 }
  RVSH : TwbSignature = 'RVSH'; { New To Starfield }
  RWDS : TwbSignature = 'RWDS'; { New to Fallout 76 0.2.782.0 }
  SADD : TwbSignature = 'SADD'; { New To Fallout 4 }
  SAIA : TwbSignature = 'SAIA'; { New To Starfield }
  SAKD : TwbSignature = 'SAKD'; { New To Fallout 4 }
  SAPT : TwbSignature = 'SAPT'; { New To Fallout 4 }
  SCCM : TwbSignature = 'SCCM'; { New To Fallout 76 }
  SCCO : TwbSignature = 'SCCO'; { New To Fallout 4 }
  SCDA : TwbSignature = 'SCDA';
  SCEN : TwbSignature = 'SCEN';
  SCFC : TwbSignature = 'SCFC'; { New To Fallout 76 }
  SCFL : TwbSignature = 'SCFL'; { New To Fallout 76 }
  SCHR : TwbSignature = 'SCHR';
  SCOL : TwbSignature = 'SCOL'; { Unused in Skyrim, but contained in Skyrim.esm }
  SCPI : TwbSignature = 'SCPI'; { New To Starfield }
  SCPP : TwbSignature = 'SCPP'; { New To Starfield }
  SCPT : TwbSignature = 'SCPT'; { Unused in Skyrim, but contained in Skyrim.esm }
  SCQS : TwbSignature = 'SCQS'; { New To Fallout 4 }
  SCRI : TwbSignature = 'SCRI';
  SCRL : TwbSignature = 'SCRL';
  SCRN : TwbSignature = 'SCRN';
  SCRO : TwbSignature = 'SCRO';
  SCRV : TwbSignature = 'SCRV';
  SCSN : TwbSignature = 'SCSN'; { New To Fallout 4 }
  SCSP : TwbSignature = 'SCSP'; { New To Starfield }
  SCTX : TwbSignature = 'SCTX';
  SCVR : TwbSignature = 'SCVR';
  SDCT : TwbSignature = 'SDCT'; { New to Fallout 76 }
  SDLT : TwbSignature = 'SDLT'; { New To Starfield }
  SDSC : TwbSignature = 'SDSC'; { New to Skyrim }
  SECH : TwbSignature = 'SECH'; { New To Fallout 76, Starfield }
  SFBK : TwbSignature = 'SFBK'; { New To Starfield }
  SFPC : TwbSignature = 'SFPC'; { New To Starfield }
  SFPT : TwbSignature = 'SFPT'; { New To Starfield }
  SFTR : TwbSignature = 'SFTR'; { New To Starfield }
  SGEN : TwbSignature = 'SGEN'; { New To Starfield }
  SGNM : TwbSignature = 'SGNM'; { New to Fallout 4 }
  SHOU : TwbSignature = 'SHOU';
  SHRT : TwbSignature = 'SHRT'; { New to Skyrim }
  SHWB : TwbSignature = 'SHWB'; { New To Starfield }
  SKIL : TwbSignature = 'SKIL'; { New to Fallout 4 }
  SLCP : TwbSignature = 'SLCP';
  SLGM : TwbSignature = 'SLGM';
  SLPD : TwbSignature = 'SLPD';
  SLSD : TwbSignature = 'SLSD';
  SMBN : TwbSignature = 'SMBN';
  SMEN : TwbSignature = 'SMEN';
  SMLS : TwbSignature = 'SMLS'; { New To Starfield }
  SMQN : TwbSignature = 'SMQN';
  SNAM : TwbSignature = 'SNAM';
  SNBH : TwbSignature = 'SNBH'; { New To Starfield }
  SNCT : TwbSignature = 'SNCT';
  SNDD : TwbSignature = 'SNDD';
  SNDR : TwbSignature = 'SNDR';
  SNDX : TwbSignature = 'SNDX';
  SNFG : TwbSignature = 'SNFG'; { New To Fallout 76 }
  SNMV : TwbSignature = 'SNMV'; { New to Skyrim }
  SNOT : TwbSignature = 'SNOT'; { New To Starfield }
  SNST : TwbSignature = 'SNST'; { New To Fallout 76 }
  SNTP : TwbSignature = 'SNTP'; { New To Fallout 76 }
  SODA : TwbSignature = 'SODA'; { New To Starfield }
  SOFT : TwbSignature = 'SOFT'; { New to Skyrim }
  SOPM : TwbSignature = 'SOPM';
  SOUL : TwbSignature = 'SOUL';
  SOUN : TwbSignature = 'SOUN';
  SPCH : TwbSignature = 'SPCH'; { New To Starfield }
  SPCT : TwbSignature = 'SPCT'; { New to Skyrim }
  SPDF : TwbSignature = 'SPDF'; { New To Starfield }
  SPED : TwbSignature = 'SPED'; { New To Skyrim }
  SPEL : TwbSignature = 'SPEL';
  SPEX : TwbSignature = 'SPEX'; { New To Starfield }
  SPGD : TwbSignature = 'SPGD';
  SPIT : TwbSignature = 'SPIT';
  SPKW : TwbSignature = 'SPKW'; { New To Starfield }
  SPKY : TwbSignature = 'SPKY'; { New To Starfield }
  SPLO : TwbSignature = 'SPLO';
  SPMA : TwbSignature = 'SPMA'; { New To Starfield }
  SPMV : TwbSignature = 'SPMV'; { New To Skyrim }
  SPOR : TwbSignature = 'SPOR'; { New to Skyrim }
  SPPI : TwbSignature = 'SPPI'; { New To Fallout 76 0.2.626.7 }
  SPPK : TwbSignature = 'SPPK'; { New To Starfield }
  SPPQ : TwbSignature = 'SPPQ'; { New To Starfield }
  SPPT : TwbSignature = 'SPPT'; { New To Fallout 76 0.2.626.7 }
  SPQU : TwbSignature = 'SPQU'; { New To Starfield }
  SPRK : TwbSignature = 'SPRK'; { New To Starfield }
  SPRP : TwbSignature = 'SPRP'; { New To Starfield }
  SPRW : TwbSignature = 'SPRW'; { New To Starfield }
  SPWI : TwbSignature = 'SPWI'; { New To Starfield }
  SPWN : TwbSignature = 'SPWN'; { New To Fallout 76 }
  SRAC : TwbSignature = 'SRAC'; { New to Fallout 4 }
  SRAF : TwbSignature = 'SRAF'; { New to Fallout 4 }
  SRAN : TwbSignature = 'SRAN'; { New To Starfield }
  SRGN : TwbSignature = 'SRGN'; { New To Fallout 76 }
  SSPN : TwbSignature = 'SSPN'; { New to Fallout 4 }
  STAD : TwbSignature = 'STAD'; { New To Starfield }
  STAE : TwbSignature = 'STAE'; { New To Starfield }
  STAG : TwbSignature = 'STAG'; { New to Fallout 4 }
  STAT : TwbSignature = 'STAT';
  STBH : TwbSignature = 'STBH'; { New To Starfield }
  STCP : TwbSignature = 'STCP'; { New to Fallout 4 }
  STDT : TwbSignature = 'STDT'; { New To Starfield }
  STHD : TwbSignature = 'STHD'; { New To Fallout 76 }
  STIJ : TwbSignature = 'STIJ';
  STKD : TwbSignature = 'STKD'; { New to Fallout 4 }
  STLS : TwbSignature = 'STLS'; { New To Starfield }
  STMP : TwbSignature = 'STMP'; { New To Fallout 76 }
  STMS : TwbSignature = 'STMS'; { New To Starfield }
  STND : TwbSignature = 'STND'; { New To Fallout 76 }
  STOL : TwbSignature = 'STOL'; { New to Skyrim }
  STON : TwbSignature = 'STON'; { New To Starfield }
  STOP : TwbSignature = 'STOP'; { New to Fallout 4 }
  STPT : TwbSignature = 'STPT'; { New To Fallout 76 }
  STRD : TwbSignature = 'STRD'; { New To Starfield }
  STRT : TwbSignature = 'STRT'; { New To Starfield }
  STRV : TwbSignature = 'STRV'; { New To Starfield }
  STSC : TwbSignature = 'STSC'; { New to Fallout 4 }
  STXF : TwbSignature = 'STXF'; { New To Fallout 76 }
  SUNP : TwbSignature = 'SUNP'; { New To Starfield }
  SWFI : TwbSignature = 'SWFI'; { New To Fallout 76 }
  SWMV : TwbSignature = 'SWMV'; { New to Skyrim }
  TACT : TwbSignature = 'TACT';
  TCFU : TwbSignature = 'TCFU';
  TCLF : TwbSignature = 'TCLF';
  TCLT : TwbSignature = 'TCLT';
  TCMP : TwbSignature = 'TCMP'; { New To Starfield }
  TDAT : TwbSignature = 'TDAT'; { New To Fallout 76 }
  TDUM : TwbSignature = 'TDUM';
  TEMP : TwbSignature = 'TEMP'; { New To Starfield }
  TEND : TwbSignature = 'TEND'; { New to Fallout 4 }
  TERM : TwbSignature = 'TERM'; { New to Fallout 4 }
  TES4 : TwbSignature = 'TES4';
  TETC : TwbSignature = 'TETC'; { New To Starfield }
  TETI : TwbSignature = 'TETI'; { New to Fallout 4 }
  TIAS : TwbSignature = 'TIAS'; { New to Skyrim }
  TIFC : TwbSignature = 'TIFC'; { New To Skyrim }
  TIFL : TwbSignature = 'TIFL'; { New To Starfield }
  TINC : TwbSignature = 'TINC'; { New to Skyrim }
  TIND : TwbSignature = 'TIND'; { New to Skyrim }
  TINI : TwbSignature = 'TINI'; { New to Skyrim }
  TINL : TwbSignature = 'TINL'; { New to Skyrim }
  TINP : TwbSignature = 'TINP'; { New to Skyrim }
  TINT : TwbSignature = 'TINT'; { New to Skyrim }
  TINV : TwbSignature = 'TINV'; { New to Skyrim }
  TIQS : TwbSignature = 'TIQS'; { New to Fallout 4 }
  TIRS : TwbSignature = 'TIRS'; { New to Skyrim }
  TLOD : TwbSignature = 'TLOD'; { New to Fallout 4 }
  TMEE : TwbSignature = 'TMEE';
  TMLM : TwbSignature = 'TMLM'; { New To Starfield }
  TMPP : TwbSignature = 'TMPP'; { New To Starfield }
  TMVT : TwbSignature = 'TMVT'; { New To Starfield }
  TNAM : TwbSignature = 'TNAM';
  TODD : TwbSignature = 'TODD'; { New To Starfield }
  TOFT : TwbSignature = 'TOFT'; { New to Fallout 4 }
  TPIC : TwbSignature = 'TPIC';
  TPLT : TwbSignature = 'TPLT';
  TPTA : TwbSignature = 'TPTA'; { New To Fallout 4 }
  TRAE : TwbSignature = 'TRAE'; { New To Fallout 76 }
  TRAV : TwbSignature = 'TRAV'; { New To Starfield }
  TRDA : TwbSignature = 'TRDA'; { New To Fallout 4 }
  TRDT : TwbSignature = 'TRDT';
  TREE : TwbSignature = 'TREE';
  TRES : TwbSignature = 'TRES';
  TRGT : TwbSignature = 'TRGT';
  TRNS : TwbSignature = 'TRNS'; { New To Fallout 4 }
  TROT : TwbSignature = 'TROT'; { New To Starfield }
  TSCE : TwbSignature = 'TSCE'; { New To Fallout 4 }
  TSLT : TwbSignature = 'TSLT'; { New To Fallout 76 }
  TTEB : TwbSignature = 'TTEB'; { New To Fallout 4 }
  TTEC : TwbSignature = 'TTEC'; { New To Fallout 4 }
  TTED : TwbSignature = 'TTED'; { New To Fallout 4 }
  TTEF : TwbSignature = 'TTEF'; { New To Fallout 4 }
  TTET : TwbSignature = 'TTET'; { New To Fallout 4 }
  TTGE : TwbSignature = 'TTGE'; { New To Fallout 4 }
  TTGP : TwbSignature = 'TTGP'; { New To Fallout 4 }
  TVDT : TwbSignature = 'TVDT'; { New To Skyrim }
  TWAT : TwbSignature = 'TWAT'; { New To Skyrim }
  TX00 : TwbSignature = 'TX00';
  TX01 : TwbSignature = 'TX01';
  TX02 : TwbSignature = 'TX02';
  TX03 : TwbSignature = 'TX03';
  TX04 : TwbSignature = 'TX04';
  TX05 : TwbSignature = 'TX05';
  TX06 : TwbSignature = 'TX06'; { New To Skyrim }
  TX07 : TwbSignature = 'TX07'; { New To Skyrim }
  TX08 : TwbSignature = 'TX08'; { New To Fallout 76 }
  TX09 : TwbSignature = 'TX09'; { New To Fallout 76 }
  TX10 : TwbSignature = 'TX10'; { New To Fallout 76 }
  TX16 : TwbSignature = 'TX16'; { New To Starfield }
  TX17 : TwbSignature = 'TX17'; { New To Starfield }
  TX19 : TwbSignature = 'TX19'; { New To Starfield }
  TXST : TwbSignature = 'TXST';
 &TYPE : TwbSignature = 'TYPE'; { New To Starfield }
  UIFL : TwbSignature = 'UIFL'; { New To Fallout 76 }
  UITE : TwbSignature = 'UITE'; { New To Fallout 76 }
  UITO : TwbSignature = 'UITO'; { New To Fallout 76 }
  UITV : TwbSignature = 'UITV'; { New To Fallout 76 }
  UIUS : TwbSignature = 'UIUS'; { New To Fallout 76 }
  UNAM : TwbSignature = 'UNAM';
  UNES : TwbSignature = 'UNES'; { New To Skyrim }
  UNWP : TwbSignature = 'UNWP'; { New To Fallout 4 }
  UTIL : TwbSignature = 'UTIL'; { New To Fallout 76 }
  UX00 : TwbSignature = 'UX00'; { New To Starfield }
  VANM : TwbSignature = 'VANM';
  VATS : TwbSignature = 'VATS';
  VBCY : TwbSignature = 'VBCY'; { New To Fallout 76 }
  VCLR : TwbSignature = 'VCLR';
  VCRY : TwbSignature = 'VCRY'; { New To Fallout 76 }
  VENC : TwbSignature = 'VENC'; { New To Skyrim }
  VEND : TwbSignature = 'VEND'; { New To Skyrim }
  VENG : TwbSignature = 'VENG'; { New To Fallout 76 }
  VENP : TwbSignature = 'VENP'; { New To Fallout 76 }
  VENR : TwbSignature = 'VENR'; { New To Fallout 76 }
  VENV : TwbSignature = 'VENV'; { New To Skyrim }
  VHGT : TwbSignature = 'VHGT';
  VISI : TwbSignature = 'VISI'; { New To Fallout 4 }
  VLMS : TwbSignature = 'VLMS'; { New To Starfield }
  VMAD : TwbSignature = 'VMAD';
  VNAM : TwbSignature = 'VNAM';
  VNML : TwbSignature = 'VNML';
  VOLI : TwbSignature = 'VOLI'; { New To Fallout 76 }
  VONL : TwbSignature = 'VONL'; { New To Fallout 76 }
  VORN : TwbSignature = 'VORN'; { New To Starfield }
  VORV : TwbSignature = 'VORV'; { New To Starfield }
  VOVS : TwbSignature = 'VOVS'; { New To Starfield }
  VREN : TwbSignature = 'VREN'; { New To Fallout 76 }
  VTCK : TwbSignature = 'VTCK';
  VTEX : TwbSignature = 'VTEX';
  VTXT : TwbSignature = 'VTXT';
  VTYP : TwbSignature = 'VTYP';
  VX00 : TwbSignature = 'VX00'; { New To Starfield }
  WAAM : TwbSignature = 'WAAM'; { New To Fallout 76 }
  WABB : TwbSignature = 'WABB'; { New To Starfield }
  WAIM : TwbSignature = 'WAIM'; { New To Starfield }
  WAIT : TwbSignature = 'WAIT'; { New To Skyrim }
  WAM2 : TwbSignature = 'WAM2'; { New To Starfield }
  WAMB : TwbSignature = 'WAMB'; { New To Starfield }
  WAMD : TwbSignature = 'WAMD'; { New To Fallout 4 }
  WASH : TwbSignature = 'WASH'; { New To Starfield }
  WATR : TwbSignature = 'WATR';
  WAUD : TwbSignature = 'WAUD'; { New To Starfield }
  WAVD : TwbSignature = 'WAVD'; { New To Fallout 76 }
  WAVE : TwbSignature = 'WAVE'; { New To Fallout 76 }
  WBAR : TwbSignature = 'WBAR'; { New To Starfield }
  WBDT : TwbSignature = 'WBDT'; { New to Skyrim }
  WCHG : TwbSignature = 'WCHG'; { New To Starfield }
  WCTR : TwbSignature = 'WCTR'; { New To Skyrim }
  WDMG : TwbSignature = 'WDMG'; { New To Starfield }
  WEAP : TwbSignature = 'WEAP';
  WED0 : TwbSignature = 'WED0'; { New To Starfield }
  WED1 : TwbSignature = 'WED1'; { New To Starfield }
  WFIR : TwbSignature = 'WFIR'; { New To Starfield }
  WFLG : TwbSignature = 'WFLG'; { New To Starfield }
  WGDR : TwbSignature = 'WGDR'; { New To Fallout 4 }
  WGEN : TwbSignature = 'WGEN'; { New To Starfield }
  WHGT : TwbSignature = 'WHGT'; { New To Fallout 76 }
  WKMF : TwbSignature = 'WKMF'; { New To Starfield }
  WKMV : TwbSignature = 'WKMV'; { New to Skyrim }
  WLEV : TwbSignature = 'WLEV'; { New To Fallout 4 }
  WLST : TwbSignature = 'WLST';
  WMAP : TwbSignature = 'WMAP'; { New To Fallout 4 }
  WMAT : TwbSignature = 'WMAT'; { New To Starfield }
  WMCT : TwbSignature = 'WMCT'; { New To Fallout 76 }
  WMEL : TwbSignature = 'WMEL'; { New To Starfield }
  WMI1 : TwbSignature = 'WMI1';
  WMI2 : TwbSignature = 'WMI2';
  WMI3 : TwbSignature = 'WMI3';
  WMKA : TwbSignature = 'WMKA'; { New To Starfield }
  WMS1 : TwbSignature = 'WMS1';
  WMS2 : TwbSignature = 'WMS2';
  WMSD : TwbSignature = 'WMSD'; { New To Starfield }
  WMSI : TwbSignature = 'WMSI'; { New To Starfield }
  WMSS : TwbSignature = 'WMSS'; { New To Starfield }
  WMTI : TwbSignature = 'WMTI'; { New To Starfield }
  WNAM : TwbSignature = 'WNAM';
  WNM1 : TwbSignature = 'WNM1';
  WNM2 : TwbSignature = 'WNM2';
  WNM3 : TwbSignature = 'WNM3';
  WNM4 : TwbSignature = 'WNM4';
  WNM5 : TwbSignature = 'WNM5';
  WNM6 : TwbSignature = 'WNM6';
  WNM7 : TwbSignature = 'WNM7';
  WOOP : TwbSignature = 'WOOP';
  WRLD : TwbSignature = 'WRLD';
  WRLO : TwbSignature = 'WRLO'; { New To Starfield }
  WSED : TwbSignature = 'WSED'; { New To Starfield }
  WSLT : TwbSignature = 'WSLT'; { New To Starfield }
  WSPR : TwbSignature = 'WSPR'; { New To Fallout 76 }
  WTED : TwbSignature = 'WTED'; { New To Starfield }
  WTFG : TwbSignature = 'WTFG'; { New To Fallout 76 }
  WTFM : TwbSignature = 'WTFM'; { New To Starfield }
  WTHR : TwbSignature = 'WTHR';
  WTHS : TwbSignature = 'WTHS'; { New To Starfield }
  WTMX : TwbSignature = 'WTMX'; { New To Fallout 76 }
  WTRM : TwbSignature = 'WTRM'; { New To Starfield }
  WTUR : TwbSignature = 'WTUR'; { New To Starfield }
  WVAR : TwbSignature = 'WVAR'; { New To Starfield }
  WVIS : TwbSignature = 'WVIS'; { New To Starfield }
  WWED : TwbSignature = 'WWED'; { New To Starfield }
  WX00 : TwbSignature = 'WX00'; { New To Starfield }
  WZMD : TwbSignature = 'WZMD'; { New To Fallout 4 }
  XACR : TwbSignature = 'XACR'; { EXTRA_ACTIVATEREF. 12 bytes }
  XACT : TwbSignature = 'XACT'; { EXTRA_ACTION. 4 bytes }
  XALD : TwbSignature = 'XALD'; { New To Starfield }
  XALG : TwbSignature = 'XALG'; { New To Fallout 76, Starfield }
  XALP : TwbSignature = 'XALP'; { New To Skyrim }
  XAMC : TwbSignature = 'XAMC'; { New To Fallout 4 }
  XAMT : TwbSignature = 'XAMT';
  XAPD : TwbSignature = 'XAPD';
  XAPR : TwbSignature = 'XAPR';
  XASP : TwbSignature = 'XASP'; { New To Fallout 4 }
  XATO : TwbSignature = 'XATO';
  XATP : TwbSignature = 'XATP'; { New To Fallout 4 }
  XATR : TwbSignature = 'XATR'; { New To Dawnguard }
  XBLT : TwbSignature = 'XBLT'; { New To Fallout 76. EXTRA_BUILTBY }
  XBPO : TwbSignature = 'XBPO'; { New To Starfield }
  XBPS : TwbSignature = 'XBPS'; { New To Starfield }
  XBSD : TwbSignature = 'XBSD'; { New To Fallout 4 }
  XCAS : TwbSignature = 'XCAS';
  XCCM : TwbSignature = 'XCCM';
  XCDD : TwbSignature = 'XCDD'; { New To Starfield }
  XCET : TwbSignature = 'XCET';
  XCGD : TwbSignature = 'XCGD'; { New To Starfield }
  XCHG : TwbSignature = 'XCHG'; //EXTRA_CHARGE
  XCIB : TwbSignature = 'XCIB'; { New To Starfield }
  XCIM : TwbSignature = 'XCIM';
  XCLA : TwbSignature = 'XCLA'; { New To Starfield }
  XCLC : TwbSignature = 'XCLC';
  XCLD : TwbSignature = 'XCLD'; { New To Starfield }
  XCLL : TwbSignature = 'XCLL';
  XCLP : TwbSignature = 'XCLP';
  XCLR : TwbSignature = 'XCLR';
  XCLW : TwbSignature = 'XCLW';
  XCMD : TwbSignature = 'XCMD'; { New To Fallout 76 }
  XCMO : TwbSignature = 'XCMO';
  XCMT : TwbSignature = 'XCMT';
  XCNT : TwbSignature = 'XCNT';
  XCOL : TwbSignature = 'XCOL'; { New To Starfield }
  XCPF : TwbSignature = 'XCPF'; { New To Fallout 76 }
  XCRI : TwbSignature = 'XCRI'; { New To Fallout 4 }
  XCRP : TwbSignature = 'XCRP'; { New To Fallout 76 }
  XCVL : TwbSignature = 'XCVL'; { New To Skyrim }
  XCVR : TwbSignature = 'XCVR'; { New To Fallout 4 }
  XCWM : TwbSignature = 'XCWM'; { New To Starfield }
  XCWT : TwbSignature = 'XCWT';
  XCZA : TwbSignature = 'XCZA'; { New To Skyrim }
  XCZC : TwbSignature = 'XCZC'; { New To Skyrim }
  XCZR : TwbSignature = 'XCZR'; { New To Skyrim }
  XDCR : TwbSignature = 'XDCR';
  XDTF : TwbSignature = 'XDTF'; { New To Starfield }
  XDTS : TwbSignature = 'XDTS'; { New To Starfield }
  XEED : TwbSignature = 'XEED'; { New To Starfield }
  XEMI : TwbSignature = 'XEMI';
  XEMP : TwbSignature = 'XEMP'; { New To Starfield }
  XESP : TwbSignature = 'XESP';
  XEZN : TwbSignature = 'XEZN';
  XFLG : TwbSignature = 'XFLG'; { New To Fallout 76 }
  XFVC : TwbSignature = 'XFVC'; { New To Skyrim }
  XGDR : TwbSignature = 'XGDR'; { New To Fallout 4 }
  XGDS : TwbSignature = 'XGDS'; { New To Starfield }
  XGLB : TwbSignature = 'XGLB';
  XGOM : TwbSignature = 'XGOM'; { New To Starfield }
  XHLP : TwbSignature = 'XHLP';
  XHLT : TwbSignature = 'XHLT'; { New To Fallout 4 }
  XHOR : TwbSignature = 'XHOR'; { New To Skyrim. EXTRA_HORSE. 4 bytes }
  XHTW : TwbSignature = 'XHTW'; { New To Skyrim }
  XIBS : TwbSignature = 'XIBS';
  XILL : TwbSignature = 'XILL'; { New To Skyrim }
  XILS : TwbSignature = 'XILS'; { New To Fallout 76 }
  XILW : TwbSignature = 'XILW'; { New To Fallout 4 }
  XIS2 : TwbSignature = 'XIS2'; { New To Skyrim }
  XISR : TwbSignature = 'XISR'; { New To Fallout 76 }
  XKPD : TwbSignature = 'XKPD'; { New To Fallout 76 }
  XLBD : TwbSignature = 'XLBD'; { New To Starfield }
  XLCD : TwbSignature = 'XLCD'; { New To Starfield }
  XLCM : TwbSignature = 'XLCM';
  XLCN : TwbSignature = 'XLCN'; { New To Skyrim }
  XLFD : TwbSignature = 'XLFD'; { New To Starfield }
  XLGD : TwbSignature = 'XLGD'; { New To Starfield }
  XLIB : TwbSignature = 'XLIB'; { New To Skyrim }
  XLIG : TwbSignature = 'XLIG'; { New To Skyrim }
  XLKR : TwbSignature = 'XLKR';
  XLKT : TwbSignature = 'XLKT'; { New To Fallout 4 }
  XLLD : TwbSignature = 'XLLD'; { New To Starfield }
  XLLV : TwbSignature = 'XLLV'; { New To Fallout 76 }
  XLMS : TwbSignature = 'XLMS'; { New To Starfield }
  XLOC : TwbSignature = 'XLOC';
  XLOD : TwbSignature = 'XLOD';
  XLRD : TwbSignature = 'XLRD'; { New To Starfield }
  XLRL : TwbSignature = 'XLRL'; { New To Skyrim }
  XLRM : TwbSignature = 'XLRM';
  XLRT : TwbSignature = 'XLRT'; { New To Skyrim }
  XLSM : TwbSignature = 'XLSM'; { New To Starfield }
  XLTW : TwbSignature = 'XLTW';
  XLVD : TwbSignature = 'XLVD'; { New To Starfield }
  XLWT : TwbSignature = 'XLWT'; { New To Fallout 76 }
  XLYR : TwbSignature = 'XLYR'; { New To Fallout 4 }
  XMBO : TwbSignature = 'XMBO';
  XMBP : TwbSignature = 'XMBP';
  XMBR : TwbSignature = 'XMBR';
  XMPM : TwbSignature = 'XMPM'; { New To Starfield }
  XMRC : TwbSignature = 'XMRC';
  XMRK : TwbSignature = 'XMRK';
  XMSP : TwbSignature = 'XMSP'; { New To Fallout 4 }
  XNAM : TwbSignature = 'XNAM';
  XNDP : TwbSignature = 'XNDP';
  XNSE : TwbSignature = 'XNSE'; { New To Starfield }
  XOCP : TwbSignature = 'XOCP';
  XORD : TwbSignature = 'XORD';
  XOWN : TwbSignature = 'XOWN';
  XPCK : TwbSignature = 'XPCK'; { New To Fallout 76 }
  XPCS : TwbSignature = 'XPCS'; { New To Starfield }
  XPDD : TwbSignature = 'XPDD'; { New To Fallout 4 }
  XPDO : TwbSignature = 'XPDO'; { New To Starfield }
  XPLK : TwbSignature = 'XPLK'; { New To Fallout 4 }
  XPLL : TwbSignature = 'XPLL'; { New To Starfield }
  XPOD : TwbSignature = 'XPOD';
  XPPA : TwbSignature = 'XPPA';
  XPPS : TwbSignature = 'XPPS'; { New To Fallout 76 }
  XPRD : TwbSignature = 'XPRD';
  XPRI : TwbSignature = 'XPRI'; { New To Fallout 4 }
  XPRM : TwbSignature = 'XPRM';
  XPSL : TwbSignature = 'XPSL'; { EXTRA_PACKAGESTARTLOC }
  XPTL : TwbSignature = 'XPTL';
  XPWR : TwbSignature = 'XPWR';
  XRAD : TwbSignature = 'XRAD';
  XRDO : TwbSignature = 'XRDO'; { New To Fallout 4 }
  XRDS : TwbSignature = 'XRDS';
  XRFE : TwbSignature = 'XRFE'; { New To Starfield }
  XRFG : TwbSignature = 'XRFG'; { New To Fallout 4 }
  XRGB : TwbSignature = 'XRGB';
  XRGD : TwbSignature = 'XRGD';
  XRMR : TwbSignature = 'XRMR';
  XRNK : TwbSignature = 'XRNK';
  XRTM : TwbSignature = 'XRTM'; { New To Fallou76. EXTRA_TELEPORTMARKER. 4 bytes }
  XSAD : TwbSignature = 'XSAD'; { New To Starfield }
  XSCL : TwbSignature = 'XSCL';
  XSED : TwbSignature = 'XSED'; { New To Fallout76. EXTRA_SEED. 4 or 1 bytes long }
  XSL1 : TwbSignature = 'XSL1'; { New To Starfield }
  XSPC : TwbSignature = 'XSPC'; { New To Skyrim }
  XSRD : TwbSignature = 'XSRD';
  XSRF : TwbSignature = 'XSRF';
  XTEL : TwbSignature = 'XTEL';
  XTNM : TwbSignature = 'XTNM'; { New To Skyrim }
  XTRG : TwbSignature = 'XTRG';
  XTRI : TwbSignature = 'XTRI';
  XTV2 : TwbSignature = 'XTV2'; { New To Starfield }
  XVL2 : TwbSignature = 'XVL2'; { New To Starfield }
  XVOI : TwbSignature = 'XVOI'; { New To Starfield }
  XWCN : TwbSignature = 'XWCN'; { New To Skyrim }
  XWCS : TwbSignature = 'XWCS'; { New To Skyrim }
  XWCU : TwbSignature = 'XWCU'; { New To Skyrim }
  XWEM : TwbSignature = 'XWEM'; { New To Skyrim }
  XWPG : TwbSignature = 'XWPG'; { New To Fallout 4 }
  XWPK : TwbSignature = 'XWPK'; { New To Fallout 76 }
  XWPN : TwbSignature = 'XWPN'; { New To Fallout 4 }
  XWRC : TwbSignature = 'XWRC'; { New To Fallout 76 }
  XX00 : TwbSignature = 'XX00'; { New To Starfield }
  XXXX : TwbSignature = 'XXXX';
  YNAM : TwbSignature = 'YNAM';
  YX00 : TwbSignature = 'YX00'; { New To Starfield }
  ZNAM : TwbSignature = 'ZNAM';
  ZOOM : TwbSignature = 'ZOOM'; { New To Fallout 4 }
  _00_IAD : TwbSignature = #$00'IAD';
  _01_IAD : TwbSignature = #$01'IAD';
  _02_IAD : TwbSignature = #$02'IAD';
  _03_IAD : TwbSignature = #$03'IAD';
  _04_IAD : TwbSignature = #$04'IAD';
  _05_IAD : TwbSignature = #$05'IAD';
  _06_IAD : TwbSignature = #$06'IAD';
  _07_IAD : TwbSignature = #$07'IAD';
  _08_IAD : TwbSignature = #$08'IAD';
  _09_IAD : TwbSignature = #$09'IAD';
  _0A_IAD : TwbSignature = #$0A'IAD';
  _0B_IAD : TwbSignature = #$0B'IAD';
  _0C_IAD : TwbSignature = #$0C'IAD';
  _0D_IAD : TwbSignature = #$0D'IAD';
  _0E_IAD : TwbSignature = #$0E'IAD';
  _0F_IAD : TwbSignature = #$0F'IAD';
  _10_IAD : TwbSignature = #$10'IAD';
  _11_IAD : TwbSignature = #$11'IAD';
  _12_IAD : TwbSignature = #$12'IAD';
  _13_IAD : TwbSignature = #$13'IAD';
  _14_IAD : TwbSignature = #$14'IAD';
  _30_0TX : TwbSignature = #$30'0TX'; {00TX}
  _31_0TX : TwbSignature = #$31'0TX'; {10TX}
  _32_0TX : TwbSignature = #$32'0TX'; {20TX}
  _33_0TX : TwbSignature = #$33'0TX'; {30TX}
  _34_0TX : TwbSignature = #$34'0TX'; {40TX}
  _35_0TX : TwbSignature = #$35'0TX'; {50TX}
  _36_0TX : TwbSignature = #$36'0TX'; {60TX}
  _37_0TX : TwbSignature = #$37'0TX'; {70TX}
  _38_0TX : TwbSignature = #$38'0TX'; {80TX}
  _39_0TX : TwbSignature = #$39'0TX'; {90TX}
  _3A_0TX : TwbSignature = #$3A'0TX'; {:0TX}
  _3B_0TX : TwbSignature = #$3B'0TX'; {;0TX}
  _3C_0TX : TwbSignature = #$3C'0TX'; {<0TX}
  _3D_0TX : TwbSignature = #$3D'0TX'; {=0TX}
  _3E_0TX : TwbSignature = #$3E'0TX'; {>0TX}
  _3F_0TX : TwbSignature = #$3F'0TX'; {?0TX}
  _40_0TX : TwbSignature = #$40'0TX'; {@0TX}
  _40_IAD : TwbSignature = #$40'IAD';
  _41_IAD : TwbSignature = #$41'IAD';
  _42_IAD : TwbSignature = #$42'IAD';
  _43_IAD : TwbSignature = #$43'IAD';
  _44_IAD : TwbSignature = #$44'IAD';
  _45_IAD : TwbSignature = #$45'IAD';
  _46_IAD : TwbSignature = #$46'IAD';
  _47_IAD : TwbSignature = #$47'IAD';
  _48_IAD : TwbSignature = #$48'IAD';
  _49_IAD : TwbSignature = #$49'IAD';
  _4A_IAD : TwbSignature = #$4A'IAD';
  _4B_IAD : TwbSignature = #$4B'IAD';
  _4C_IAD : TwbSignature = #$4C'IAD';
  _4D_IAD : TwbSignature = #$4D'IAD';
  _4E_IAD : TwbSignature = #$4E'IAD';
  _4F_IAD : TwbSignature = #$4F'IAD';
  _50_IAD : TwbSignature = #$50'IAD';
  _51_IAD : TwbSignature = #$51'IAD';
  _52_IAD : TwbSignature = #$52'IAD';
  _53_IAD : TwbSignature = #$53'IAD';
  _54_IAD : TwbSignature = #$54'IAD';

implementation

end.
